insert into question values(0,0,1,'党的十八届五中全会提出“十三五”时期我国发展的指导思想的中心是（  ）','B',1);
insert into question values(1,0,2,'中共十八届四中全会通过的《中共中央关于全面推进依法治国若干重大问题的决定》指出，社会主义市场经济本质上是（    ）','C',1);
insert into question values(2,0,3,'中共十八届四中全会通过的《中共中央关于全面推进依法治国若干重大问题的决定》提出，中国特色社会主义最本质的特征，社会主义法治最根本的保证是(    )','D',1);
insert into question values(3,0,4,'中共十八届四中全会提出，法治的生命线是(   )','C',1);
insert into question values(4,0,5,'中共十八届四中全会指出，司法公正对社会公正具有重要引领作用，司法不公对社会公正具有致命破坏作用。必须完善司法管理体制和司法权力运行机制，规范司法行为，加强对司法活动的监督，努力让人民群众在每一个司法案件中感受到（   ）','A',1);
insert into question values(5,0,6,'2013年11月12日，中国共产党十八届三中全会通过的《中国共产党中央关于全面深化改革若干重大问题的决定》指出，经济体制改革是全面深化改革的重点，核心问题是（  ）','B',1);
insert into question values(6,0,7,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》指出全面深化改革的重点是(  )','B',1);
insert into question values(7,0,8,'2013年11月9日到12日，中共十八届三中全会在北京召开，这次全会的主题是(  )','A',1);
insert into question values(8,0,9,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》提出，制约城乡发展一体化的主要障碍是( )','B',1);
insert into question values(9,0,10,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》提出，使市场在资源配置中起决定性作用的基础是(  )','D',1);
insert into question values(10,0,11,'中共十八届四中全会通过的《中共中央关于全面推进依法治国若干重大问题的决定》提出，全面推进依法治国，总目标是(    )','A',1);
insert into question values(11,1,1,'党的中央领导真正认识到马克思主义中国化的重要性是在1935年遵义会议以后，而就全党来讲，则是在（    ）以后','C',1);
insert into question values(12,1,2,'1938年，毛泽东在党的（  　）上作的题为《论新阶段》的政治报告中最先提出了“马克思主义中国化”这个命题','D',1);
insert into question values(13,1,3,'经过（  　），马克思主义中国化的思想成为全党的共识','A',1);
insert into question values(14,1,4,'党的七大通过的《中国共产党章程》在总纲中确定，以马克思列宁主义的理论与中国革命的实践之统一的思想——（  　），作为我们党一切工作的指南','A',1);
insert into question values(15,1,5,'（   ）是马克思主义中国化的第一个重大理论成果，是中国化的马克思主义','A',1);
insert into question values(16,1,6,'马克思主义中国化，就是将（    ）','D',1);
insert into question values(17,1,7,'马克思主义作为一种外来思想文化传入中国，要使它能为中国人民广泛接受，并在实践中发挥指导作用，就必须寻找到一种为中国人民所能理解和接受的（  　）','C',1);
insert into question values(18,1,8,'党的十一届三中全会以来，以邓小平为主要代表的中国共产党人，在总结国内外社会主义建设的历史经验特别是改革开放以来的新鲜经验的基础上，初步回答了（  　）这个首要的基本的理论问题','C',1);
insert into question values(19,1,9,'党的十三届四中全会以来，以（  　）为代表的中国共产党人，根据国内外形势和党的历史方位的新变化，进一步回答了什么是社会主义、怎样建设社会主义和建设什么样的党、怎样建设党的问题，深化了对社会主义的认识，形成了“三个代表”重要思想','C',1);
insert into question values(20,1,10,'党的十六大以来，以胡锦涛为总书记的党中央立足社会主义初级阶段基本国情，总结我国发展实践，借鉴国外发展经验，适应新的发展要求提出了科学发展观等重大战略思想，进一步回答了（  　）这一关系到中国未来前途和命运的重大问题，深化了党对共产党执政规律、社会主义建设规律、人类社会发展规律的认识','A',1);
insert into question values(21,1,11,'毛泽东思想和中国特色社会主义理论体系虽然形成于不同的历史时期，面对着不同的历史任务，具有不同的具体内容，但在基本精神上都是一致的，都坚持（  　）','D',1);
insert into question values(22,1,12,'在当代中国，（  　）是全党和全国各族人民的精神支柱','C',1);
insert into question values(23,1,13,'（  　）是中国共产党在改革开放历史新时期的伟大实践中，不断坚持和发展马克思主义的结果，是马克思主义中国化的最新成果','B',1);
insert into question values(24,1,14,'实践已经并将继续证明，只有高举（  　）旗帜，才能发展中国、发展社会主义，实现中华民族的伟大复兴','B',1);
insert into question values(25,1,15,'在当代中国，只有（    ）旗帜而不是别的什么旗帜能够最大限度地团结和凝聚不同社会阶层、不同利益群体人们的智慧和力量，能够解决当代中国的前途命运问题','A',1);
insert into question values(26,1,16,'（  　）是关系党的事业兴衰成败的首要问题','D',1);
insert into question values(27,1,17,'党的十一届三中全会以后，由中国共产党团结和带领全国各族人民共同开创的（  　），是进一步实现民族振兴、国家富强和人民幸福的唯一正确的道路','B',1);
insert into question values(28,1,18,'党的（  　）对中国特色社会主义道路作出了明确界定','B',1);
insert into question values(29,1,19,'我们党能够在新时期开创出中国特色社会主义道路，其历史根据是（ 　）','A',1);
insert into question values(30,1,20,'在当代中国，坚持马克思主义，就必须坚持中国特色社会主义理论体系；坚持中国特色社会主义理论体系，就是（    ）','C',1);
insert into question values(31,1,21,'20世纪上半叶，帝国主义战争与无产阶级革命的时代主题，是（    ）形成的时代背景','B',1);
insert into question values(32,1,22,'中国共产党领导的革命和建设的实践，是（   ）形成的实践基础','B',1);
insert into question values(33,1,23,'1945年（    ），把毛泽东思想确立为党的指导思想','A',1);
insert into question values(34,1,24,'毛泽东思想不是在个别的方面，而是在许多方面以其独创性理论丰富和发展了马克思列宁主义，构成一个博大精深的科学思想体系。它有着坚实的中国化马克思主义哲学思想的理论基础，其核心和精髓就是（    ）','A',1);
insert into question values(35,1,25,'（    ）是反映中国新民主主义革命客观规律的完备的理论形态，是毛泽东思想达到成熟的主要标志','B',1);
insert into question values(36,1,26,'1981年党的（    ）做出的《关于建国以来党的若干历史问题的决议》，对毛泽东和毛泽东思想的历史地位做出了科学的、实事求是的评价','A',1);
insert into question values(37,1,27,'（    ）曾指出：没有毛泽东，至少我们中国人民还要在黑暗中摸索更长的时间','B',1);
insert into question values(38,1,28,'20世纪70年代以来，新科技革命和世界经济不断发展，国际形势和世界政治格局发生了重大变革。（    ）逐渐成为时代的主题，为我国一心一意搞社会主义现代化建设，实行改革开发，借鉴和吸收人类社会创造的一切文明成果提供了良好机遇','C',1);
insert into question values(39,1,29,'我国改革开放以来（    ），是邓小平理论形成和发展的历史和现实根据','B',1);
insert into question values(40,1,30,'粉碎“四人帮”后，邓小平领导了（    ）。1978年12月，他在中央工作会议上作了重要讲话，强调全党要解放思想，实事求是，团结一致向前看','D',1);
insert into question values(41,1,31,'党的十一届三中全会重新确立了（    ）的思想路线，做出了把党和国家的工作重点转移到社会主义现代化建设上来和实行改革开放的战略决策，由此开创了我国历史发展的新时期','A',1);
insert into question values(42,1,32,'1982年，在党的十二大上，邓小平正式提出了（    ）的命题','B',1);
insert into question values(43,1,33,'1987年（    ）第一次比较系统地论述了社会主义初级阶段的理论，制定了党在社会主义初级阶段的“一个中心，两个基本点”的基本路线','B',1);
insert into question values(44,1,34,'1992年初，邓小平在（    ）中，从理论上深刻地回答了长期困扰和束缚人们思想的许多重大历史问题，把改革开放和现代化建设推向了新境界','D',1);
insert into question values(45,1,35,'为了把建设中国特色社会主义事业全面推向21世纪，1997年9月召开的（    ）正式提出“邓小平理论”这一科学概念，科学阐述了邓小平理论的历史地位和指导意义','B',1);
insert into question values(46,1,36,'（    ）是邓小平在领导改革开放和现代化建设中，不断提出和反复思考的首要的基本的理论问题。而搞清楚这个问题，关键是要在科学总结历史经验和坚持社会主义基本制度的基础上进一步认清社会主义的本质','C',1);
insert into question values(47,1,37,'党的十一届三中全会以来指定了一系列新的方针政策，这些方针政策概括起来就是（    ），是决定中国命运的重大决策，是新时期中国最鲜明的特点','C',1);
insert into question values(48,1,38,'（    ）是对马克思列宁主义、毛泽东思想、邓小平理论的继承和发展， 反映了当代世界和中国的发展变化对党和国家工作的新要求，是加强和改进党的建设、推进我国社会主义自我完善和发展的强大理论武器','D',1);
insert into question values(49,1,39,'贯彻“三个代表”重要思想，关键在坚持与时俱进，核心在（  　），本质在坚持执政为民','A',1);
insert into question values(50,1,40,'（  　）把“三个代表”重要思想同马克思列宁主义、毛泽东思想、邓小平理论一起写入党章','C',1);
insert into question values(51,1,41,'“三个代表”是统一的整体，相互联系、相互促进。（  　）是发展先进文化的基础，是实现最广大人民根本利益','D',1);
insert into question values(52,1,42,'（  　）是发展先进生产力和实现最广大人民根本利益的重要思想保证','C',1);
insert into question values(53,1,43,'党在新世纪新阶段最重要的任务，就是（  　）','A',1);
insert into question values(54,1,44,'（ 　）是对中国共产党的三代中央领导集体关于发展的重要思想的继承和发展，是马克思主义关于发展的世界观和方法论的集中体现','D',1);
insert into question values(55,1,45,'（  　）基本国情是提出科学发展观的根本依据','D',1);
insert into question values(56,1,46,'我国在新世纪新阶段的（  　）是提出科学发展观的现实基础','A',1);
insert into question values(57,1,47,'当代世界的发展实践和发展理念是提出（ 　）的重要借鉴','B',1);
insert into question values(58,1,48,'2004年9月，（  　）通过的《中共中央关于加强党的执政能力建设的决定》，把树立和落实科学发展观作为提高党的执政能力的重要内容','B',1);
insert into question values(59,1,49,'2005年10月，（  　）通过的《中共中央关于制定国民经济和社会发展第十一个五年规划的建议》强调，要坚定不移地以科学发展观统领经济社会发展全局，坚持以人为本，转变发展观念、创新发展模式、提高发展质量，把经济社会发展切实转入全面协调可持续发展的轨道','C',1);
insert into question values(60,1,50,'2006年3月，全国人大十届四次会议通过的《中华人民共和国国民经济和社会发展第十一个五年规划纲要》中指出，“十一五”时期促进国民经济持续快速协调健康发展和社会全面进步，关键是要牢固树立和全面落实（  　）','B',1);
insert into question values(61,1,51,'（   ）把科学发展观写入了党章','D',1);
insert into question values(62,1,52,'科学发展观，第一要义是（   ），核心是以人为本，基本要求是全面协调可持续，根本方法是统筹兼顾','C',1);
insert into question values(63,1,53,'科学发展观的核心是（    ）','D',1);
insert into question values(64,1,54,'以人为本，就是以最广大人民的（    ）为本','B',1);
insert into question values(65,1,55,'科学发展观的基本要求是（    ）','B',1);
insert into question values(66,1,56,'科学发展观的根本方法是（    ）','C',1);
insert into question values(67,1,57,'党的十七大把包括邓小平理论、“三个代表”重要思想、科学发展观在内的科学理论体系概括为 （    ）','C',1);
insert into question values(68,1,58,'把邓小平理论确立为党的指导思想是(    )','D',1);
insert into question values(69,1,59,'中国特色社会主义的总布局是（  ）','C',1);
insert into question values(70,1,60,'十八大提出建设中国特色社会主义八大要求，其中摆在第一位的基本要求是（  ）','A',1);
insert into question values(71,1,61,'在我党历史上，第一次使用“思想路线”这一概念的是（   ）','A',1);
insert into question values(72,1,62,'毛泽东第一次使用“思想路线”这一概念是在（    ）','B',1);
insert into question values(73,1,63,'20世纪30年代，中国共产党内最早提出反对教条主义任务的领导人是(    )','A',1);
insert into question values(74,1,64,'曾明确指出“社会实践是检验真理的唯一标准”的是（    ）','C',1);
insert into question values(75,1,65,'对实事求是首先做出马克思主义的解释，并把它确立为中国共产党的思想路线的是（　　）','B',1);
insert into question values(76,1,66,'毛泽东初步界定中国共产党人的思想路线的基本含义是在（    ）','B',1);
insert into question values(77,1,67,'在全党确立实事求是的思想路线是在党的（    ）','A',1);
insert into question values(78,1,68,'毛泽东初步界定中国共产党人思想路线基本含义的著作是（    ）','A',1);
insert into question values(79,1,69,'实事求是的“是”指的是（    ）','D',1);
insert into question values(80,1,70,'实事求是的“求”指的是（     ）','A',1);
insert into question values(81,1,71,'实事求是的“实事”指的是（    ）','C',1);
insert into question values(82,1,72,'毛泽东最早深刻阐述认识对实践的依赖关系，对党的思想路线作了系统的哲学论证的哲学著作是（    ）','C',1);
insert into question values(83,1,73,'毛泽东最早系统地阐述唯物辩证法思想，对党的思想路线作了系统的哲学论证的哲学著作是（   ）','B',1);
insert into question values(84,1,74,'毛泽东对实事求是的科学含义作出马克思主义界定的著作是（     ）','D',1);
insert into question values(85,1,75,'毛泽东第一次对实事求是的科学含义作出马克思主义界定，并把能否坚持实事求是提到有没有党性或党性纯不纯的高度，是在（    ）','C',1);
insert into question values(86,1,76,'实事求是思想路线的重新确立是在党的（    ）','C',1);
insert into question values(87,1,77,'在全面进行社会主义建设的过程中，毛泽东曾针对“大跃进”的“左”的错误，为把实事求是的精神恢复起来，号召全党（     ）','B',1);
insert into question values(88,1,78,'“实践是检验真理唯一标准”的大讨论是在（   ）','B',1);
insert into question values(89,1,79,'在“文化大革命”结束后中国向何处去的重大历史关头，邓小平在拨乱反正过程中首先抓住的关键环节是（    ）','C',1);
insert into question values(90,1,80,'1977年邓小平在写给党中央的信中强调要完整、准确地理解毛泽东思想，率先批评了（    ）','A',1);
insert into question values(91,1,81,' 1978年邓小平在中央工作会议上作的《解放思想，实事求是，团结一致向前看》的重要讲话，重新确立了党的（    ）','A',1);
insert into question values(92,1,82,'邓小平在重新确立实事求是思想路线时特别强调的是要（    ）','B',1);
insert into question values(93,1,83,'邓小平指出：“一个党，一个国家，一个民族，如果一切从本本出发，思想僵化，迷信盛行，那它就不能前进，它的生机就停止了，就要亡党亡国。”这段话，非常深刻地阐明了（   ）','D',1);
insert into question values(94,1,84,'邓小平认为，在一切工作中要真正坚持实事求是，正确以马克思列宁主义、毛泽东思想，解决过去遗留的问题和新出现的一系列问题，首先必须（    ）','D',1);
insert into question values(95,1,85,'邓小平理论的精髓是 (    )','B',1);
insert into question values(96,1,86,'邓小平对党的思想路线的贡献在于（    ）','B',1);
insert into question values(97,1,87,'江泽民对新形势下坚持实事求是思想路线提出了新要求，强调马克思主义最重要的理论品质是（    ）','C',1);
insert into question values(98,1,88,'胡锦涛进一步深化了对实事求是思想路线的认识，提出必须大力弘扬（    ）','D',1);
insert into question values(99,1,89,'党的实事求是思想路线的实质和核心是（    ）','C',1);
insert into question values(100,1,90,'党的实事求是思想路线的前提和基础是（    ）','A',1);
insert into question values(101,1,91,'党的实事求是思想路线的根本途径和方法是（    ）','B',1);
insert into question values(102,1,92,'党的实事求是思想路线的验证条件和目的是（     ）','D',1);
insert into question values(103,1,93,'92．邓小平在批判“两个凡是”错误观点时，提出必须（     ）','D',1);
insert into question values(104,1,94,'邓小平在批判“两个凡是”错误观点，强调解放思想的同时，还强调（    ）','B',1);
insert into question values(105,1,95,'邓小平指出，马克思主义的辩证唯物主义和历史唯物主义，用毛主席的话来讲就是（    ）','C',1);
insert into question values(106,1,96,'马克思主义中国化理论成果的精髓是（    ）','C',1);
insert into question values(107,1,97,'贯穿于马克思主义中国化理论成果始终的是（   ）','B',1);
insert into question values(108,1,98,'邓小平坚决反对“两个凡是”的观点，明确指出，检验真理的唯一标准是（    ）','C',1);
insert into question values(109,1,99,'江泽民指出：“马克思主义具有强大生命力的奥秘，就在于它具有（    ）的理论品质。”','B',1);
insert into question values(110,1,100,'江泽民曾强调指出，马克思主义最重要的理论品质是（    ）','C',1);
insert into question values(111,1,101,'与时俱进就是党的全部理论和全部工作要体现时代性，把握规律性，（    ）','D',1);
insert into question values(112,1,102,'提出：“实践的观点是辩证唯物论的认识论之第一的和基本的观点。”的是（    ）','A',1);
insert into question values(113,1,103,'强调：“判定认识或理论之是否真理，不是以主观上的觉得如何而定，而是以客观上社会实践的结果如何而定。真理的标准只能是社会的实践。”的是（     ）','A',1);
insert into question values(114,1,104,'明确指出：“把马克思主义的普遍真理同我国的具体实际结合起来，走自己的路，建设有中国特色的社会主义，这就是我们总结长期历史经验得出的基本结论。”的是（    ）','B',1);
insert into question values(115,1,105,'提出：“大胆吸收和借鉴人类社会创造的一切文明成果，吸收和借鉴当今世界各国包括资本主义发达国家的一切反映现代社会化生产规律的先进经营方式管理方式。”的是（    ）','B',1);
insert into question values(116,1,106,'坚持实事求是的思想路线，就要大力弘扬（    ）精神，推进理论创新，不断开拓马克思主义的新境界。','B',1);
insert into question values(117,1,107,'实事求是思想路线的根本体现是 （    ）','A',1);
insert into question values(118,1,108,'马克思主义不是一个由既定不变的概念、结论和公式构成的狭隘、封闭、僵化的体系，而是一个富有自我更新和生长活力的、开放的、具有强大实践功能的科学体系。以上这段表述所揭示的是马克思主义的(    )','B',1);
insert into question values(119,1,109,'不断开拓马克思主义理论发展的新境界，就要求党的全部理论和工作，要紧跟时代的步伐，用马克思主义的宽广眼界观察世界；要更加符合实践发展的客观规律；要更加开拓创新。以上这“三个要”体现的是对(     )','A',1);
insert into question values(120,1,110,'马克思主义与时俱进的理论品格表明（    ）','C',1);
insert into question values(121,1,111,'一个民族进步的灵魂，一个国家兴旺发达不竭的动力，一个政党永葆生机的源泉是（    ）','A',1);
insert into question values(122,1,112,'作为社会发展和变革先导的是实践基础上的（　　）','D',1);
insert into question values(123,1,113,'中国共产党的十六大报告指出，中国共产党坚持先进性和增强创造力的决定性因素是（　　）','A',1);
insert into question values(124,1,114,'“走自己的路，建设有中国特色的社会主义”，表明在我国社会主义建设中（    ）','A',1);
insert into question values(125,1,115,'一切从实际出发，是我们制定路线、方针的基本原则，现阶段中国最大的实际是（    ）','D',1);
insert into question values(126,1,116,'邓小平南方谈话回答了长期困扰人们思想的一系列重大认识问题，被誉为新时期第二次思想解放的宣言书，邓小平南方谈话发表的时间是（     ）','D',1);
insert into question values(127,1,117,'落脚于（    ）','A',1);
insert into question values(128,1,118,'坚持实事求是的思想路线，在中国革命、建设和改革问题上，最根本的就是（    ）','A',1);
insert into question values(129,2,1,'1939年，毛泽东第一次明确提出“新民主主义”这一命题的文章是 （    ）','B',1);
insert into question values(130,2,2,'主张将民主革命和社会主义革命“毕其功于一役”的主要代表是（    ）','C',1);
insert into question values(131,2,3,'中国共产党明确提出反帝反封建民主革命纲领的会议是(    )','B',1);
insert into question values(132,2,4,'新民主主义的政治目标是（   ）','D',1);
insert into question values(133,2,5,'中国近代民主革命的主力军是（    ）','C',1);
insert into question values(134,2,6,'毛泽东明确地把官僚资本主义列为新民主主义革命对象之一的著作是       （    ）','D',1);
insert into question values(135,2,7,'新民主主义革命总路线的核心是（     ）','A',1);
insert into question values(136,2,8,'新民主主义革命的指导思想是（    ）','C',1);
insert into question values(137,2,9,'新民主主义国家的政体是（     ）','B',1);
insert into question values(138,2,10,'新民主主义社会的国体是（     ）','D',1);
insert into question values(139,2,11,'新民主主义革命的前途是(      )','B',1);
insert into question values(140,2,12,'实现无产阶级领导权的根本保证是(      )','D',1);
insert into question values(141,2,13,'毛泽东完整地提出新民主主义革命总路线和总政策的著作是(      )','C',1);
insert into question values(142,2,14,'对中国社会的半殖民地性质和中国革命应分两步走等有了初步认识，在马克思列宁主义和中国实际相结合的道路上迈出了可喜的第一步是在（    ）','B',1);
insert into question values(143,2,15,'近代中国半殖民地半封建社会的基本特点和基本国情(最基本的国情)是（    ）','D',1);
insert into question values(144,2,16,'在半殖民地半封建中国社会经济生活中占明显优势的是(     )','A',1);
insert into question values(145,2,17,'近代中国贫穷落后的总根源，也是阻碍中国社会发展的根本原因是（    ）','A',1);
insert into question values(146,2,18,'近代中国革命的两大历史任务是（      ）','C',1);
insert into question values(147,2,19,'伟大的近代和现代中国革命是在下列基本矛盾的基础上发生和发展起来的(     )','D',1);
insert into question values(148,2,20,'中国革命由旧民主主义向新民主主义转变的标志是(      )','A',1);
insert into question values(149,2,21,'中国旧民主主义革命与新民主主义革命的根本区别是(      )','B',1);
insert into question values(150,2,22,'中国革命的主要对象是(     )','D',1);
insert into question values(151,2,23,'新民主主义革命的直接目标是（     ）','A',1);
insert into question values(152,2,24,'毛泽东认为，中国过去的一切革命斗争成效甚少，其根本原因是(     )','D',1);
insert into question values(153,2,25,'毛泽东明确地把官僚资本主义同帝国主义、封建主义一起并列为中国革命的三大对象之一是在(     )','D',1);
insert into question values(154,2,26,'导致近代中国落后挨打的内在原因是(     )','B',1);
insert into question values(155,2,27,'中国革命既是对外推翻帝国主义压迫的民族革命，又是对内推翻封建主义的民主革命，这两大任务的关系是（    ）','C',1);
insert into question values(156,2,28,'中国革命的最广大的动力是(     )','A',1);
insert into question values(157,2,29,'在民主革命时期，广大知识分子和青年学生从他们的家庭出身、政治立场、生活条件看，多数可归入(    )','A',1);
insert into question values(158,2,30,'小资产阶级属于(     )','D',1);
insert into question values(159,2,31,'民主革命时期，中共对民族资产阶级采取又联合又斗争的政策，这是由于民族资产阶级具有(    )','D',1);
insert into question values(160,2,32,'中国工人阶级比中国资产阶级资格要老，因而它的社会力量和社会基础也更广大些，这是因为(    )','B',1);
insert into question values(161,2,33,'中国工人阶级不但是民主革命的最基本的动力，而且是革命的领导力量，是由以下因素决定的(    )','D',1);
insert into question values(162,2,34,'五四运动后的新民主主义革命从其性质上来说仍然是资产阶级民主革命，是','',1);
insert into question values(163,2,35,'中国革命的前途问题实际就是(    )','A',1);
insert into question values(164,2,36,'把民主革命与社会主义革命“毕其功于一役”，其错误在于（    ）','B',1);
insert into question values(165,2,37,'中共中央八七会议召开的地点在(    )','C',1);
insert into question values(166,2,38,'毛泽东提出今后党“要非常注意军事，须知政权是由枪杆子中取得的”的重','',1);
insert into question values(167,2,39,'人民军队建设的最根本的原则是（    ）','C',1);
insert into question values(168,2,40,'奠定新型人民军队的基础并由此开始确立党指挥枪的原则是在(     )','C',1);
insert into question values(169,2,41,'人民军队的生命线是 （    ）','A',1);
insert into question values(170,2,42,'无产阶级治军的根本是(     )','D',1);
insert into question values(171,2,43,'毛泽东从中国国情出发认为，人民战争的主体是（     ）','B',1);
insert into question values(172,2,44,'毛泽东关于人民战争战略战术思想的核心是(      )','B',1);
insert into question values(173,2,45,'解放战争时期，毛泽东提出十大军事原则的核心是(    )','C',1);
insert into question values(174,2,46,'中国共产党从中国半殖民地半封建社会的国情出发，逐渐认识到中国革命的','',1);
insert into question values(175,2,47,'中国的武装斗争实质是(     )','A',1);
insert into question values(176,2,48,'第一次国共合作的政治基础（共同纲领）是(    )','C',1);
insert into question values(177,2,49,'中国共产党正式确定共产党员以个人身份加入国民党以实现国共合作方针的','',1);
insert into question values(178,2,50,'1927年以后，中国共产党在统一战线中忽视了联合民族资产阶级的政策，所犯的错误是(     )','A',1);
insert into question values(179,2,51,'第一次国共合作正式建立的标志是(     )','B',1);
insert into question values(180,2,52,'中国共产党确定建立抗日民族统一战线策略方针的会议是(      )','D',1);
insert into question values(181,2,53,'毛泽东思想关于党的建设最核心的内容和最主要的特点是(     )','B',1);
insert into question values(182,2,54,'在我们党内，无产阶级思想与非无产阶级思想的矛盾最主要表现在(     )','A',1);
insert into question values(183,2,55,'中国共产党创造的加强党的思想建设的好形式是(     )','B',1);
insert into question values(184,2,56,'坚持民主集中制原则的核心是(     )','D',1);
insert into question values(185,2,57,'首次明确提出了执政党建设问题的会议是(    )','C',1);
insert into question values(186,2,58,'中国共产党首次对党的优良作风作了简明概括的会议是(     )','D',1);
insert into question values(187,2,59,'正确处理党内矛盾的基本方针和原则是(     )','B',1);
insert into question values(188,2,60,'中国共产党领导的统一战线问题，实质上是无产阶级在革命中的(     )','A',1);
insert into question values(189,2,61,'包括英美派大地主大资产阶级在内的统一战线是（    ）','C',1);
insert into question values(190,2,62,'中国共产党在统一战线中处理同资产阶级关系的正确方针是(     )','A',1);
insert into question values(191,2,63,'毛泽东在《〈共产党人〉发刊词》中所说的“伟大的工程”是指(     )','A',1);
insert into question values(192,2,64,'毛泽东在《〈共产党人〉发刊词》中论述了中国共产党在中国革命中的三个基本问题、三个主要法宝，这就是(      )','C',1);
insert into question values(193,2,65,'1942年中国共产党在延安开展的整风运动其中心任务是(     )','A',1);
insert into question values(194,2,66,'国民革命失败后，以毛泽东为代表的中国共产党人逐步将革命的重心(    )','B',1);
insert into question values(195,2,67,'中国民主革命走向胜利的主要战略基地是(     )','B',1);
insert into question values(196,2,68,'中国共产党领导革命武装建立的全国第一个农村革命根据地是(    )','B',1);
insert into question values(197,2,69,'农村包围城市、武装夺取政权道路思想成为全党的共识是在(    )','C',1);
insert into question values(198,2,70,'中国的武装斗争实质是(    )','A',1);
insert into question values(199,2,71,'毛泽东在《中国的红色政权为什么能够存在？》等文章中指出：中国的红色政权能够存在和发展的最根本的原因是(    )','A',1);
insert into question values(200,2,72,'农村包围城市、武装夺取政权革命道路的理论基本形成的标志是(      )','B',1);
insert into question values(201,2,73,'新民主主义革命的基本问题和中心内容是(     )','A',1);
insert into question values(202,2,74,'毛泽东确立了“以乡村为中心”的观点的文章是(    )','B',1);
insert into question values(203,3,1,'党在过渡时期的总路线、总任务是（    ）','B',1);
insert into question values(204,3,2,'1956年我国在生产资料所有制的社会主义改造基本完成后，开始进入（ ）','D',1);
insert into question values(205,3,3,'新中国成立之初，我国人民民主专政的性质是（    ）','A',1);
insert into question values(206,3,4,'我国从新民主主义进入社会主义的标志是（   ）','B',1);
insert into question values(207,3,5,'1953年到1956年中国国内的主要矛盾是（   ）','C',1);
insert into question values(208,3,6,'对资本主义工商业社会主义改造的正确方针是（  ）','D',1);
insert into question values(209,3,7,'下列对新民主主义社会的说法中最准确的是（  ）','D',1);
insert into question values(210,3,8,'中华人民共和国的成立，标志着中国已经进入了（  ）','B',1);
insert into question values(211,3,9,'新民主主义社会属于（   ）','A',1);
insert into question values(212,3,10,'民主革命任务完成后，中国开始了由（  ）向社会主义的转变','D',1);
insert into question values(213,3,11,'过渡时期总路线的主体是（  ）','D',1);
insert into question values(214,3,12,'新民主主义革命在全国胜利及土地革命在全国完成后，国内的主要矛盾是（  ）','C',1);
insert into question values(215,3,13,'新中国独立、富强的当然要求和必要条件是（   ）','A',1);
insert into question values(216,3,14,'中国共产党对个体农业实行社会主义改造的方针是（  ）','C',1);
insert into question values(217,3,15,'对资本主义工商业社会主义改造形式是（  ）','A',1);
insert into question values(218,3,16,'我国对资本主义工商业的社会主义改造采取的政策是（  ）','B',1);
insert into question values(219,3,17,'我国农业合作化采取了循序渐进的步骤是（  ）','B',1);
insert into question values(220,3,18,'20世纪中国第二次历史性巨变的标志是（  ）','C',1);
insert into question values(221,3,19,'中国向社会主义过渡的物质基础是（   ）','A',1);
insert into question values(222,3,20,'新民主主义社会的主要特征是（  ）','A',1);
insert into question values(223,3,21,'党在过渡时期总路线最显著的特征是（   ）','A',1);
insert into question values(224,3,22,'中国民族资产阶级在社会主义改造时期仍有两面性，其表现为（  ）','C',1);
insert into question values(225,3,23,'剥削制度在我国被消灭的标志是（   ）','C',1);
insert into question values(226,3,24,'1949年中华人民共和国的建立，标志着中国从半殖民地半封建社会进入(    )','B',1);
insert into question values(227,3,25,'我国由新民主主义向社会主义转变的时期是指(   )','B',1);
insert into question values(228,3,26,'1949年到1952年，党领导人民集中力量恢复国民经济，继续完成(  )','D',1);
insert into question values(229,3,27,'党在农业社会主义改造中对待富农的政策是(   )','B',1);
insert into question values(230,3,28,'我党对官僚资本和民族资本采取的政策分别是(   )','B',1);
insert into question values(231,3,29,'我国对农业进行社会主义改造的循序渐进的步骤是(    )','C',1);
insert into question values(232,3,30,'国家资本主义企业生产关系发生根本变化是在(   )','B',1);
insert into question values(233,3,31,'中国民族资产阶级在社会主义革命时期的两面性是(   )','D',1);
insert into question values(234,3,32,'社会主义改造时期国内的主要矛盾是(   )','C',1);
insert into question values(235,3,33,'党在“过渡时期总路线”中提到的过渡时期是指从(    )','D',1);
insert into question values(236,3,34,'过渡时期总路线的主体是(   )','B',1);
insert into question values(237,3,35,'新民主主义社会中，处于领导地位的经济成分是(   )','C',1);
insert into question values(238,3,36,'新中国成立之初，我国社会主义国营经济建立的主要途径与手段是(   )','A',1);
insert into question values(239,3,37,'我国剥削制度被消灭的标志是(   )','D',1);
insert into question values(240,3,38,'我国进入社会主义初级阶段的重要标志是(   )','B',1);
insert into question values(241,3,39,'社会主义改造完成后，我国政治生活的主题是(   )','C',1);
insert into question values(242,3,40,'社会主义改造完成后我国国内的主要矛盾是(   )','A',1);
insert into question values(243,3,41,'社会主义改造完成后，党的中心任务是(   )','B',1);
insert into question values(244,3,42,'我国对个体手工业进行社会主义改造的主要方式是(    )','D',1);
insert into question values(245,3,43,'我国新民主主义革命阶段的基本结束和社会主义革命阶段开始的标志是(    )','A',1);
insert into question values(246,3,44,'新民主主义社会是一个(    )','B',1);
insert into question values(247,3,45,'１９４９年中华人民共和国的建立，标志着中国从半殖民地半封建社会进入(    )','C',1);
insert into question values(248,3,46,'新民主主义社会属于(    )','C',1);
insert into question values(249,3,47,'建国初期，我国社会主义国营经济建立的最主要途径和手段是(    )','B',1);
insert into question values(250,3,48,'新民主主义社会存在着多种经济成分，其中在国民经济中占绝对优势的是(    )','C',1);
insert into question values(251,3,49,'新民主主义社会的主要矛盾是(    )','B',1);
insert into question values(252,3,50,'过渡时期的总路线被概括为“一化三改造”，“一化”的含义是指(    )','D',1);
insert into question values(253,3,51,'提出过渡时期社会主义建设和社会主义改造同时并举的是在(    )','B',1);
insert into question values(254,3,52,'解放初期我国国民经济得到恢复，民主革命的遗留任务完成仅用了三年时间，即(    )','D',1);
insert into question values(255,3,53,'毛泽东正式提出过渡时期总路线和总任务是在(    )','B',1);
insert into question values(256,3,54,'我国过渡时期的含义是指(    )','D',1);
insert into question values(257,3,55,'党提出过渡时期总路线的物质基础是(    )','A',1);
insert into question values(258,3,56,'党提出过渡时期总路线的重要依据是(    )','B',1);
insert into question values(259,3,57,'党提出过渡时期总路线的重要因素是(    )','C',1);
insert into question values(260,3,58,'党在过渡时期对农业进行社会主义改造的重要准备条件是(    )','C',1);
insert into question values(261,3,59,'党在过渡时期对农业进行社会主义改造的群众基础是(    )','A',1);
insert into question values(262,3,60,'我国农业社会主义改造的第一个阶段主要是建立(    )','A',1);
insert into question values(263,3,61,'我国农业社会主义改造的第二个阶段主要是建立(    )','B',1);
insert into question values(264,3,62,'我国农业社会主义改造的第三个阶段主要是建立(    )','C',1);
insert into question values(265,3,63,'我国对手工业的社会主义改造的第一步是(    )','B',1);
insert into question values(266,3,64,'我国对手工业的社会主义改造的第二步是(    )','A',1);
insert into question values(267,3,65,'我国对手工业的社会主义改造的第三步是(    )','C',1);
insert into question values(268,3,66,'我国在手工业的社会主义改造过程中所办的手工业供销小组的性质属于(    )','C',1);
insert into question values(269,3,67,'我国在手工业的社会主义改造过程中所办的手工业供销合作社的性质属于(    )','B',1);
insert into question values(270,3,68,'我国在手工业的社会主义改造过程中所办的手工业生产合作社的性质属于(    )','A',1);
insert into question values(271,3,69,'我国对资本主义工商业的社会主义改造经历了三个步骤，第一步采取的措施是(    )','A',1);
insert into question values(272,3,70,'我国对资本主义工商业的社会主义改造经历了三个步骤，第二步采取的措施是(    )','B',1);
insert into question values(273,3,71,'在对资本主义工商业的改造中，国家对私营工商业实行委托加工、计划订货、统购包销、代销等形式，使其生产、经营开始纳入国家计划的轨道。利润分配上实行“四马分肥”政策，工人在企业中的地位也发生改变。这使得企业(    )','B',1);
insert into question values(274,3,72,'在对资本主义工商业的改造中，国家向私营企业投资入股，企业生产资料由国家和资本家共同所有，利润分配仍然实行“四马分肥”，国家向企业派出公方代表，与工人、资本家共同管理和改造企业，公方代表居领导地位。这时的企业性质(    )','C',1);
insert into question values(275,3,73,'国家在公私合营后对合营企业进行清产核资，定股定息，委派人员负责企业的生产管理，同时按企业资本的股份额给原工商业者定息。这时的企业性质属于(    )','D',1);
insert into question values(276,3,74,'我国对资本主义工商业的社会主义改造完成的标志是(    )','D',1);
insert into question values(277,4,1,'在探索我国社会主义建设道路的问题上，毛泽东关于正确处理经济建设和社会发展中一系列重大关系的重要著作是（     ）','B',1);
insert into question values(278,4,2,'毛泽东提出社会主义社会基本矛盾和两类不同性质矛盾的学说的著作是（     ）','A',1);
insert into question values(279,4,3,'在探索适合中国国情的社会主义经济建设道路上，提出“三个主体，三个补充”思想的是（    ）','D',1);
insert into question values(280,4,4,'在探索适合中国国情的社会主义道路问题上，主要在农业生产中实行同产量联系起来的责任制的是（   ）','A',1);
insert into question values(281,4,5,'在探索适合中国国情的社会主义道路的问题上，提出整顿工业企业，改善和加强企业管理，实行职工代表大会制等观点的是（   ）','C',1);
insert into question values(282,4,6,'在探索适合中国国情的社会主义道路的问题上，提出我国知识分子绝大多数已经是劳动人民的知识分子，科学技术在我国现代化建设中具有关键性作用观点的是（   ）','B',1);
insert into question values(283,4,7,'在探索适合中国国情的社会主义道路问题上，第一次提出社会主义本质概念的是（   ）','C',1);
insert into question values(284,4,8,'1956年苏共二十大以后，毛泽东认为它对我们最重要的教益是（   ）','C',1);
insert into question values(285,4,9,'1957年2月，毛泽东作了《关于正确处理人民内部矛盾的问题》的讲话，提出了（    ）','D',1);
insert into question values(286,4,10,'“文化大革命”期间，毛泽东仍然提出了一些比较正确的思想观点。他提出（   ）','C',1);
insert into question values(287,4,11,'第一次明确提出要实现四个现代化的任务是在（    ）','C',1);
insert into question values(288,4,12,'1956年4-5月，毛泽东先后在中共中央政治局扩大会议和最高国务会议上作的《论十大关系》报告中指出：“最近苏联方面暴露了他们在建设社会主义过程中的一些缺点和错误，他们走过的弯路你还想走？过去，我们就是鉴于他们的经验教训，少走了一些弯路，现在当然更要引以为戒”，这表明以毛泽东为主要代表的中国共产党人（    ）','B',1);
insert into question values(289,4,13,'《论十大关系》的发表标志着（    ）','C',1);
insert into question values(290,4,14,'毛泽东同志在《论十大关系》的报告中确定了党关于社会主义建设的一个极为重要的基本方针是（    ）','B',1);
insert into question values(291,4,15,'成为全党探索中国社会主义建设道路先声的文章，是毛泽东的（    ）','D',1);
insert into question values(292,4,16,'毛泽东在《论十大关系》的报告中指出，中国工业化道路最重要的问题是（  ）','B',1);
insert into question values(293,4,17,'（    ）是我党关于社会主义建设的一个极为重要的基本方针','A',1);
insert into question values(294,4,18,'在我国社会主义改造完成之后，政治生活中居于主导地位的矛盾是（    ）','C',1);
insert into question values(295,4,19,'（    ）在领导苏联社会主义建设的实践中，长期不承认社会主义存在矛盾','B',1);
insert into question values(296,4,20,'毛泽东认为，社会主义基本矛盾是具有（    ）的性质','D',1);
insert into question values(297,4,21,'毛泽东认为，社会主义社会基本矛盾具有“又相适应又相矛盾”的特点，其中，之所以会有相矛盾的一面，是因为(    )','D',1);
insert into question values(298,4,22,'我党的哪次会议正确分析了社会主义改造完成之后我国社会主要矛盾的变化(    )','B',1);
insert into question values(299,4,23,'新中国成立后，工人阶级与民族资产阶级之间的矛盾属于(    )','C',1);
insert into question values(300,4,24,'毛泽东指出，在处理敌我矛盾时，我们采取的方法是(   )','B',1);
insert into question values(301,4,25,'毛泽东指出，在解决人民内部矛盾时，一个总的方针是(   )','A',1);
insert into question values(302,4,26,'毛泽东指出，对于物质利益、分配方面的人民内部矛盾，应采取(    )的方针解决','C',1);
insert into question values(303,4,27,'毛泽东指出，对于民族之间的人民内部矛盾，应采取(  )的方针解决','A',1);
insert into question values(304,4,28,'毛泽东强调， （   ）是社会主义国家政治生活的主题','A',1);
insert into question values(305,4,29,'我党的哪次重要会议提出了实现国家工业化的目标(    )','A',1);
insert into question values(306,4,30,'毛泽东指出：我国社会主义建设中，(   )是经济建设的重点','A',1);
insert into question values(307,4,31,'在关于社会主义发展阶段问题上，毛泽东提出，社会主义可以被分为两个阶段，其中第二个阶段是（    ）','D',1);
insert into question values(308,4,32,'毛泽东指出，我国社会主义现代化的战略目标是（    ）','C',1);
insert into question values(309,4,33,'在经济建设中，毛泽东反复强调（   ）的方针','C',1);
insert into question values(310,4,34,'在所有制结构的调整问题上，（    ）提出了要注意发展手工业和农业多种经营的思想','D',1);
insert into question values(311,4,35,'在经济体制和运行机制的改革问题上，（  ）提出了使社会主义经济既有计划性又有多样性和灵活性的主张','C',1);
insert into question values(312,4,36,'在科学和教育问题上，我党在探索社会主义建设道路过程中，提出了（   ）的口号','C',1);
insert into question values(313,4,37,'在社会主义改造还未结束时，毛泽东就提出，在探索中国自己的社会主义建设道路过程中，要实现（   ）','B',1);
insert into question values(314,4,38,'实践证明，要正确认识社会主义社会的主要矛盾和根本任务，就要 (    )','A',1);
insert into question values(315,4,39,'党在社会主义建设道路初步探索时的经验教训表明，（   ）是社会主义事业顺利发展的政治保证','C',1);
insert into question values(316,4,40,'无产阶级政党的根本组织原则与指导党内生活的基本准则是（   ）','B',1);
insert into question values(317,4,41,'邓小平在总结近代中国的历史经验时指出：“中国在西方国家产业革命以后就变得落后了，一个重要原因就是闭关自守”。这一经验启示我们(   )','C',1);
insert into question values(318,5,1,'在社会主义思想发展史上，最早提到社会主义发展阶段问题的是(    )','C',1);
insert into question values(319,5,2,'我国制定路线、政策的出发点和根本依据是（    ）','C',1);
insert into question values(320,5,3,'社会主义初级阶段是指 （    ）','B',1);
insert into question values(321,5,4,'正确把握国情要求必须做到（    ）','A',1);
insert into question values(322,5,5,'第一次提出我国社会主义制度还处在初级的阶段的是(    )','B',1);
insert into question values(323,5,6,'对社会主义初级阶段的特征进行全面概括的是（    ）','D',1);
insert into question values(324,5,7,'我国社会主义初级阶段的主要矛盾是（    ）','C',1);
insert into question values(325,5,8,'解决社会主义初级阶段主要矛盾的根本手段是（   ）','A',1);
insert into question values(326,5,9,'第一次把社会主义初级阶段作为事关全局的基本国情加以把握，明确了这一问题是制定路线、政策的出发点和基本依据的是(      )','D',1);
insert into question values(327,5,10,'一切从实际出发，现阶段我国最大的实际是(      )','D',1);
insert into question values(328,5,11,'正确认识我国目前所处的历史阶段，是中国社会主义建设的（     ）','D',1);
insert into question values(329,5,12,'邓小平曾说：“现在虽说我们也在搞社会主义，但事实上不够格”。这说明 (     )','D',1);
insert into question values(330,5,13,'邓小平曾指出：“现在虽说我们也在搞社会主义，但事实上不够格”。所谓“不够格”，最主要是指（    ）','B',1);
insert into question values(331,5,14,'我国社会主义初级阶段是(     )','B',1);
insert into question values(332,5,15,'社会主义初级阶段是我国建设社会主义不可逾越的一个历史阶段，下列说法错误的是(    )','A',1);
insert into question values(333,5,16,'不属于社会主义初级阶段与新民主主义社会的区别的是（    ）','C',1);
insert into question values(334,5,17,'在我党的历史文献中第一次使用了“社会主义初级阶段”这一概念是(      )','A',1);
insert into question values(335,5,18,'社会主义初级阶级的历史任务，是逐步摆脱不发达状态(    )','B',1);
insert into question values(336,5,19,'我国改革开放以来取得巨大成就的根本原因之一就在于制定的路线、方针、政策合乎（    ）','C',1);
insert into question values(337,5,20,'改革开放以来在我国发生了重大变化的是（    ）','C',1);
insert into question values(338,5,21,'改革开放以来我国在诸多方面都发生了重大变化，但是没有变化的是（  ）','D',1);
insert into question values(339,5,22,'我国社会主义初级阶段的起点是（    ）','B',1);
insert into question values(340,5,23,'下列不属于社会主义初级阶段特征的是（    ）','A',1);
insert into question values(341,5,24,'社会主义初级阶段在各方面先进和落后的并存，是我国基本国情的重要特点，它决定了社会主义初级阶段的发展具有的总的基本特征是：(    )','A',1);
insert into question values(342,5,25,'我国社会主义初级阶段的时间是指（    ）','B',1);
insert into question values(343,5,26,'初级阶段长期性的根本决定因素包括（    ）','A',1);
insert into question values(344,5,27,'党的十三大在科学阐述社会主义初级阶段理论的同时，正式提出了党在社会主义初级阶段的（    )','C',1);
insert into question values(345,5,28,'党在社会主义初级阶段的基本路线的“两个基本点”是（    ）','C',1);
insert into question values(346,5,29,'对党在社会主义初级阶段的基本路线作出明确概括的是(    )','B',1);
insert into question values(347,5,30,'四项基本原则为社会主义建设提供了（　　）','C',1);
insert into question values(348,5,31,'社会主义初级阶段基本纲领和基本路线的关系，党的基本纲领是基本路线的（    ）','A',1);
insert into question values(349,5,32,'坚持党的社会主义初级阶段的基本路线100年不动摇，关键是坚持（    ）','A',1);
insert into question values(350,5,33,'我国社会主义初级阶段发展战略的出发点和归宿是（    ）','B',1);
insert into question values(351,5,34,'“一个中心，两个基本点”中的“一个中心”是指（　    ）','A',1);
insert into question values(352,5,35,'“一个中心，两个基本点”统一于（    ）','B',1);
insert into question values(353,5,36,'实现社会主义初级阶段奋斗目标的根本立足点是（    ）','D',1);
insert into question values(354,5,37,'把“和谐”与“富强民主文明”一起写入基本路线的是（     ）','D',1);
insert into question values(355,5,38,'坚持以经济建设为中心，从根本上说是由（ 　）','B',1);
insert into question values(356,5,39,'四项基本原则是 （    ）','B',1);
insert into question values(357,5,40,'改革开放是 （    ）','A',1);
insert into question values(358,5,41,'不属于四项基本原则内容的是（    ）','C',1);
insert into question values(359,5,42,'党的十五大第一次提出了党在社会主义初级阶段的（    ）','A',1);
insert into question values(360,5,43,'党在社会主义初级阶段经济领域的奋斗目标是（     ）','A',1);
insert into question values(361,5,44,'党在社会主义初级阶段政治领域的奋斗目标是（     ）','B',1);
insert into question values(362,5,45,'党在社会主义初级阶段基本路线的简明概括是（    ）','C',1);
insert into question values(363,5,46,'党在社会主义初级阶段思想文化领域的奋斗目标是（    ）','C',1);
insert into question values(364,5,47,'党在社会主义初级阶段社会领域的奋斗目标是（     ）','D',1);
insert into question values(365,5,48,'邓小平多次指出，四项基本原则的核心是坚持（　 　）','C',1);
insert into question values(366,5,49,'(     )是我们的立国之本。','A',1);
insert into question values(367,5,50,'(     )是我们的强国之路。','B',1);
insert into question values(368,5,51,'无产阶级政党的最高纲领是(    )','D',1);
insert into question values(369,5,52,'第一次提出了党在社会主义初级阶段基本纲领的是（    ）','B',1);
insert into question values(370,5,53,'党在社会主义初级阶段的基本纲领规定，建设有中国特色社会主义经济的基本目标是(    )','D',1);
insert into question values(371,6,1,'邓小平认为，在社会主义建设过程中，长期以来没有完全搞清楚的问题是（    ）','B',1);
insert into question values(372,6,2,'邓小平认为，衡量社会主义经济政策对不对的压倒一切的标准是（    ）','B',1);
insert into question values(373,6,3,'邓小平指出，社会主义最大的优越性是（   ）','B',1);
insert into question values(374,6,4,'我们过去对什么是社会主义的问题之所以没有完全搞清楚，一个重要的原因就是（   ）','C',1);
insert into question values(375,6,5,'邓小平社会主义本质理论中一个十分明显和突出的特点和创造是（   ）','A',1);
insert into question values(376,6,6,'在社会主义本质中，明确提出社会主义的根本目标是（   ）','D',1);
insert into question values(377,6,7,'党的十六大以来，以胡锦涛为总书记的党中央以马克思列宁主义、毛泽东思想、邓小平理论和“三个代表”重要思想为指导，作出了深化对社会主义本质认识的重大判断，这个判断是（   ）','C',1);
insert into question values(378,6,8,'马克思主义认为，共产主义的最终目的是（   ）','B',1);
insert into question values(379,6,9,'社会主义本质理论把我们对（    ）的认识提高到一个新的科学水平。','C',1);
insert into question values(380,6,10,'社会主义在同资本主义的较量中能否不断地巩固和发展自己，体现社会主义制度的优越性，最根本的是（   ）','B',1);
insert into question values(381,6,11,'党要承担起推动中国社会进步的历史责任，必须始终紧紧抓住执政兴国的第一要务，这个执政兴国的第一要务就是（   ）','C',1);
insert into question values(382,6,12,'邓小平指出“发展才是硬道理”，硬就硬在（   ）','D',1);
insert into question values(383,6,13,'20世纪50年代代表党中央提出“向科学进军”口号的是（   ）','C',1);
insert into question values(384,6,14,'明确提出“科学技术是第一生产力”的是（   ）','D',1);
insert into question values(385,6,15,'进入21世纪后，党中央国务院面对世界科技发展的大势作出了（   ）的决策','C',1);
insert into question values(386,6,16,'党要始终代表中国先进生产力的发展要求，努力实现生产力的跨越式发展，就必须（   ）','B',1);
insert into question values(387,6,17,'马克思主义发展史中，第一个提出科学技术是生产力的是（   ）','A',1);
insert into question values(388,6,18,'明确提出科学技术是先进生产力的集中体现和主要标志的是（   ）','C',1);
insert into question values(389,6,19,'明确提出科学技术是“推动人类文明进步的革命力量”这一重要论断的是（   ）','D',1);
insert into question values(390,6,20,'20.早在新民主主义革命时期毛泽东就提出，判断一个政党历史地位的标准是（   ）','C',1);
insert into question values(391,6,21,'“全面落实科学技术是第一生产力的思想，坚持教育为本，把科技和教育摆在经济、社会发展的重要位置，增强国家的科技实力及向现实生产力转化的能力，提高全民族的科技文化素质，把经济建设转移到依靠科技进步和提高劳动者素质的轨道上来，加速实现国家的繁荣富强”这段话体现了（   ）','A',1);
insert into question values(392,6,22,'“努力造就数以亿计的专门人才和一大批拔尖创新人才，建设规模宏大、结构合理、素质较高的人才队伍，开创人才辈出、人尽其才的新局面”，这段话体现了我党的（   ）','B',1);
insert into question values(393,6,23,'邓小平关于建设有中国特色社会主义的首要的基本的理论问题是(    )','C',1);
insert into question values(394,6,24,'邓小平明确提出社会主义本质的论断是在(    )','B',1);
insert into question values(395,6,25,'邓小平指出，在改革中社会主义必须始终坚持的两条根本原则是(    )','D',1);
insert into question values(396,6,26,'发展生产力是社会主义的(    )','A',1);
insert into question values(397,6,27,'十六大报告指出，作为党执政兴国的第一要务是(    )','C',1);
insert into question values(398,6,28,'要正确认识和把握社会主义，核心是科学认识(    )','B',1);
insert into question values(399,6,29,'体现社会主义本质的前提是(    )','A',1);
insert into question values(400,6,30,'邓小平对社会主义本质的科学概括(    )','A',1);
insert into question values(401,6,31,'邓小平明确提出社会主义本质的论断是在(  	 )','A',1);
insert into question values(402,6,32,'1992年，邓小平提出了著名论断( 	   )','D',1);
insert into question values(403,6,33,'邓小平指出，在改革中社会主义必须始终坚持的两条根本原则是(   )','B',1);
insert into question values(404,6,34,'一种社会制度是否具有优越性，从根本上说，就是看其能否( 	  )','A',1);
insert into question values(405,6,35,'发展生产力是社会主义的(   )','C',1);
insert into question values(406,6,36,'邓小平指出“贫穷不是社会主义，社会主义要消灭贫穷。”这个判断','',1);
insert into question values(407,6,37,'发展之所以成为我党执政兴国的第一要务，归根到底是因为( 	 )','A',1);
insert into question values(408,6,38,'邓小平关于怎样建设社会主义问题的论述的核心是（   ）','A',1);
insert into question values(409,6,39,'社会主义本质论是邓小平理论的（   ）','B',1);
insert into question values(410,6,40,'解决社会主义初级阶段主要矛盾的根本手段是（   ）','B',1);
insert into question values(411,6,41,'马克思主义认为，共产主义的最终目的是（    ）','A',1);
insert into question values(412,6,42,'邓小平认为中国解决所有问题的关键是要靠(     )','D',1);
insert into question values(413,6,43,'关于社会主义本质论述中“解放生产力，发展生产力”属于(    )','A',1);
insert into question values(414,6,44,'巩固和发展社会主义，充分发挥社会主义优越性的根本条件是（   ）','C',1);
insert into question values(415,6,45,'社会主义初级阶段的主要矛盾要求我们必须以（   ）','A',1);
insert into question values(416,6,46,'把党和国家的工作重点由以阶级斗争为纲转移到经济建设上来，是党的（    ）','C',1);
insert into question values(417,6,47,'以胡锦涛为首的党中央作出深化认识社会主义本质的重大判断（   ）','C',1);
insert into question values(418,6,48,'社会主义经济政策对不对，归根到底要看（   ）','A',1);
insert into question values(419,6,49,'社会主义本质理论的重要意义是（   ）','B',1);
insert into question values(420,6,50,'正式提出分“三步走”基本实现现代化的发展战略，是在党的（      ）','B',1);
insert into question values(421,6,51,'“三步走”发展战略指出，第一步人民生活（    ）','A',1);
insert into question values(422,6,52,'分“三步走”基本实现现代化的发展战略，第二步是（　　）','B',1);
insert into question values(423,6,53,'2000年国内生产总值是1980年的6倍以上，超过原定20年翻两番的目标；商品供应普遍短缺的状况根本改观；经济结构实现重大调整；基础设施薄弱的状况得到明显改善，人民生活实现了历史性跨越。这段材料表明：(      )','C',1);
insert into question values(424,6,54,'根据“三步走”发展战略，实现我国现代化的目标是在（    ）','C',1);
insert into question values(425,6,55,'根据“三步走”发展战略，到“第三步”目标实现时我国人均国内生产总值要（ 　）','B',1);
insert into question values(426,6,56,'世纪第一个10年是实现我国社会主义建设发展战略第三步目标关键的10年，在这10年中，我们要 （    ）','A',1);
insert into question values(427,6,57,'提出全面建设一个惠及十几亿人口的更高水平的小康社会的阶段是在（    ）','C',1);
insert into question values(428,6,58,'全面小康社会目标实现之时，我国（    ）','D',1);
insert into question values(429,6,59,'党提出全面建设惠及十几亿人口的更高水平的小康社会的阶段是指（   ）','B',1);
insert into question values(430,7,1,'党的最高领导机关是（  ）','B',1);
insert into question values(431,7,2,' 遵守党的(  )是遵守党的全部纪律的重要基础。','B',1);
insert into question values(432,7,3,'《中国共产党廉洁自律准则》对党员领导干部提出（  ）条廉洁自律规范。','A',1);
insert into question values(433,7,4,'《中国共产党廉洁自律准则》是党执政以来第(  )部坚持正面倡导、面向全体党员的规范全党廉洁自律工作的重要基础性法规。','A',1);
insert into question values(434,7,5,'《中国共产党廉洁自律准则》共(  )条、281字，包括导语、党员廉洁自律规范和党员领导干部廉洁自律规范等3部分。','B',1);
insert into question values(435,7,6,'《中国共产党廉洁自律准则》第一条规定是(  )。','A',1);
insert into question values(436,7,7,'《中国共产党廉洁自律准则》第二条规定是(  )。','B',1);
insert into question values(437,7,8,'《中国共产党廉洁自律准则》第三条规定是(  )。','C',1);
insert into question values(438,7,9,'《中国共产党廉洁自律准则》第四条规定是坚持(  )，享受在后，甘于奉献。','C',1);
insert into question values(439,7,10,'组织、参加旨在反对党的领导、反对社会主义制度或者敌视政府等组织的，对策划者、组织者和骨干分子，给予(  )处分。','C',1);
insert into question values(440,7,11,'组织、参加会道门或者邪教组织的，对策划者、组织者和(  )，给予开除党籍处分。','C',1);
insert into question values(441,7,12,'挑拨民族关系制造事端或者参加民族分裂活动的，对策划者、组织者和骨干分子，给予(  )分。','C',1);
insert into question values(442,7,13,'对抗组织审查，串供或者伪造、销毁、转移、隐匿证据的，(  )，给予开除党籍处分。','C',1);
insert into question values(443,7,14,'对抗组织审查，阻止他人揭发检举、提供证据材料的，情节较重的，给予(  )处分。','B',1);
insert into question values(444,7,15,'在(  )中，其言行在政治上造成恶劣影响，损害党和国家尊严、利益的，情节严重的，给予开除党籍 处分。','C',1);
insert into question values(445,7,16,'诬告陷害他人意在使他人受纪律追究的，情节较重的，给予(  )处分。（《条例》第69条）','B',1);
insert into question values(446,7,17,'违反有关规定程序(  )的，对直接责任者和领导责任者，情节严重的，给予撤销党内职务处分。','C',1);
insert into question values(447,7,18,'违反有关规定办理因私出国（境）证件、前往港澳通行证，或者未经批准出入国（边）境，情节严重的，给予(  )处分。','A',1);
insert into question values(448,7,19,'党员领导干部的配偶、子女及其配偶，违反有关规定在该党员领导干部管辖的区域或者业务范围内从事可能影响其公正执行公务的经营活动的，该党员领导干部应当按照规定予以(  )。','B',1);
insert into question values(449,7,20,'利用职权或者职务上的影响，侵占非本人经管的公私财物，或者以象征性地支付钱款等方式侵占公私财物，或者无偿、象征性地支付报酬接受服务、使用劳务，情节较重的，给予(  )处分。','B',1);
insert into question values(450,7,21,'利用职权或者职务上的影响，违反有关规定占用公物归个人使用，时间超过(  )，情节较重的，给予警告或者严重警告处分。','A',1);
insert into question values(451,7,22,'违反有关规定组织、参加用公款支付的宴请、高消费娱乐、健身活动，或者用公款购买赠送、发放礼品，对直接责任者和领导责任者，(  )，给予警告或者严重警告处分。','A',1);
insert into question values(452,7,23,'违反公务接待管理规定，超标准、超范围接待或者借机大吃大喝，对直接责任者和领导责任者，情节严重的，给予(  )处分。','B',1);
insert into question values(453,7,24,'擅自举办评比达标表彰活动或者借评比达标表彰活动收取费用的，情节严重的，给予(  )处分。','B',1);
insert into question values(454,7,25,'搞权色交易或者给予财物搞钱色交易，(  )，给予开除党籍处分。','C',1);
insert into question values(455,7,26,'在办理涉及群众事务时刁难群众、吃拿卡要，情节严重的，给予(  )处分。','C',1);
insert into question values(456,7,27,'因工作不负责任致使所管理的人员叛逃的，对直接责任者和领导责任者，情节严重的，给予(  )处分。','B',1);
insert into question values(457,7,28,'因____致使所管理的人员出走，对直接责任者和领导责任者，情节严重的，给予撤销党内职处分。','B',1);
insert into question values(458,7,29,'党员领导干部违反有关规定干预和插手司法活动、执纪执法活动，向有关地方或者部门打招呼、说情，或者以其他方式对司法活动、执纪执法活动施加影响，情节较轻的，给予(  )处分。','B',1);
insert into question values(459,7,30,'党员领导干部违反有关规定干预和插手司法活动、执纪执法活动，向有关地方或者部门打招呼、说情，或者以其他方式对司法活动、执纪执法活动施加影响，情节严重的，给予(  )处分。','C',1);
insert into question values(460,7,31,'私自留存涉及党组织关于干部选拔任用、(  )等方面资料，情节严重的，给予撤销党内职务处分。','B',1);
insert into question values(461,7,32,'在考试、录取工作中，有泄露试题、考场舞弊、涂改考卷、违规录取等违反有关规定行为，情节严重的，给予(  )处分。','C',1);
insert into question values(462,7,33,'有严重违反社会公德、家庭美德行为的，应当视具体情节给予警告直至(  )处分。','C',1);
insert into question values(463,7,34,'以下行为，哪一项不属于《中国共产党纪律处分条例》规定的范畴？（  ）','B',1);
insert into question values(464,7,35,'在党内选举中搞拉票、助选等非组织活动，情节严重的，给予（  ）处分。','C',1);
insert into question values(465,7,36,'违背社会公序良俗，在公共场所有不当行为，造成不良影响的，给予（  ）处分。','B',1);
insert into question values(466,7,37,'主动交代，是指涉嫌违纪的党员在(  )向有关组织交代自己的问题，或者在初核和立案调查其问题期间交代组织未掌握的问题。','A',1);
insert into question values(467,7,38,'在初核、立案调查过程中，涉嫌违纪的党员能够配合调查工作，如实坦白(  )的其本人主要违纪事实的，可以从轻处分。','A',1);
insert into question values(468,7,39,'党员犯罪情节轻微，人民检察院依法作出不起诉决定的，或者人民法院依法作出有罪判决并免予刑事处罚的，最低要给予(  )处分。','C',1);
insert into question values(469,7,40,'管理和监督，把纪律挺在前面，注重(  )。','A',1);
insert into question values(470,7,41,'处理违犯党纪的党组织和党员，应当实行惩戒和教育相结合，做到(  )。','A',1);
insert into question values(471,7,42,'《中国共产党纪律处分条例》适用于（  ）。','C',1);
insert into question values(472,7,43,'以下哪一项不属于党的纪律处分工作应当坚持的原则？（  ）','B',1);
insert into question values(473,7,44,'以下哪一种不属于对党员的纪律处分种类？（  ）','B',1);
insert into question values(474,7,45,'以改革创新精神全面推进党的建设新的伟大工程，必须坚持党要管党、从严治党，贯彻 （  ）的要求。','B',1);
insert into question values(475,7,46,'预备党员的预备期为（  ）。','B',1);
insert into question values(476,7,47,'预备党员的预备期，从 （  ） 算起。','C',1);
insert into question values(477,7,48,'党的最高领导机关是（  ）。','B',1);
insert into question values(478,7,49,'党的全国代表大会每（  ）年举行一次。','C',1);
insert into question values(479,7,50,'党的基层组织是党在社会基层组织中的（  ）。','A',1);
insert into question values(480,7,51,'中国共产党党员是中国工人阶级的有（  ）觉悟的先锋战士。','B',1);
insert into question values(481,7,52,'党章规定共产党员享有（  ）权利。','C',1);
insert into question values(482,7,53,'党执政后的最大危险是（  ）。','A',1);
insert into question values(483,7,54,'党章规定，申请入党的同志，必须年满（  ）岁。','C',1);
insert into question values(484,7,55,'按照党的思想建设的要求，党员不仅要在组织上入党，而且要在（  ）上入党。','B',1);
insert into question values(485,7,56,'党章规定，预备党员的预备期最长为（  ）。','C',1);
insert into question values(486,7,57,'马克思主义具有（  ）的理论品质。','C',1);
insert into question values(487,7,58,'民主集中的基础是（  ）。','D',1);
insert into question values(488,7,59,'党的根本组织原则是（  ）。','D',1);
insert into question values(489,7,60,'近代中国第一次彻底反帝反封建的革命运动是（  ）。','B',1);
insert into question values(490,7,61,'我国的根本国家制度即国体是（  ）。','B',1);
insert into question values(491,7,62,'我国多党合作和政治协商制度的基本组织形式是（  ）。','B',1);
insert into question values(492,7,63,'解决社会基本矛盾的途径和方法是（  ）。','B',1);
insert into question values(493,7,64,'（  ）是党内的最高处分。','B',1);
insert into question values(494,7,65,'中国共产党党徽为（  ）组成的图案。','A',1);
insert into question values(495,7,66,'中国共产党党员永远是（  ）的普通一员。','B',1);
insert into question values(496,7,67,'现阶段，我国社会的主要矛盾是人民日益增长的（  ）需要同落后的社会生产之间的矛盾。','D',1);
insert into question values(497,7,68,'（  ）是我们党执政兴国的第一要务。','A',1);
insert into question values(498,7,69,'社会主义初级阶段基本路线的中心是（  ）。','B',1);
insert into question values(499,7,70,'下面（  ）不是入党誓词的内容。','D',1);
insert into question values(500,7,71,'中国共产党的宗旨是（  ）。','B',1);
insert into question values(501,7,72,'我国根本的政治制度是（  ）。','B',1);
insert into question values(502,7,73,'1978年召开的党的（  ），是建国以来我党历史上具有深远意义的伟大转折。','C',1);
insert into question values(503,7,74,'党的第一个党章是在党的第（  ）次代表大会上制定的。','B',1);
insert into question values(504,7,75,'党的（  ），是党的全部工作和战斗力的基础。','C',1);
insert into question values(505,7,76,'把毛泽东思想确立为党的指导思想是在党的（  ）。','B',1);
insert into question values(506,7,77,'把邓小平理论确立为党的指导思想是在党的（  ）。','C',1);
insert into question values(507,7,78,'党必须在（  ）的范围内活动。','C',1);
insert into question values(508,7,79,'党的最大优势是（  ）。','A',1);
insert into question values(509,7,80,'加强和改进党的自身建设,要着重从（  ）上建设党','C',1);
insert into question values(510,7,81,'（  ）是解放和发展生产力的必由之路。','D',1);
insert into question values(511,7,82,'中华民族形成了以（  ）为核心的团结统一、爱好和平、勤劳勇敢、自强不息的伟大民族精神。','B',1);
insert into question values(512,7,83,'党的最高理想和最终目标是实现（  ）。','A',1);
insert into question values(513,7,84,'中国共产党是（  ）的领导核心。','C',1);
insert into question values(514,7,85,'完成祖国统一大业的基本方针是（  ）。','C',1);
insert into question values(515,7,86,'不管国际风云如何变幻，我们始终不渝地奉行（  ）的和平外交政策。','A',1);
insert into question values(516,7,87,'中国共产党在新世纪面临的三大历史任务是（  ）。','A',1);
insert into question values(517,7,88,'科学发展观的基本要求是（  ）。','B',1);
insert into question values(518,7,89,'党内监督的重点对象是（  ）。','B',1);
insert into question values(519,7,90,'党章规定，党员必须履行的义务有(  )条。','C',1);
insert into question values(520,7,91,'党章规定，党员享有的权利有(  )条。','C',1);
insert into question values(521,7,92,'科学发展观是发展中国特色社会主义必须坚持和贯彻的 (  )。','B',1);
insert into question values(522,7,93,'(  ) 是我们党执政兴国的第一要务。','A',1);
insert into question values(523,7,94,'《行政机关公务员处分条例》规定，对地方各级人民代表大会及其常务委员会选举或者决定任命的地方各级人民政府领导人员给予处分，由 ()人民政府决定。','B',1);
insert into question values(524,7,95,'根据《中国共产党纪律处分条例》，党员领导干部下列哪些行为要受到党纪处分?()','ABD',1);
insert into question values(525,7,96,'加强社会主义核心价值体系建设，坚持马克思主义指导思想，树立中国特色社会主义共同理想，弘扬以 为核心的民族精神，以 ()为核心的时代精神。','B',1);
insert into question values(526,7,97,'2015年修订的《中国共产党廉洁自律准则》和《中国共产党纪律处分条例》是对()的具体化。','B',1);
insert into question values(527,7,98,'中央委员会认为有必要，或者() 以上的省一级组织提出要求，全国代表大会可以提前举行。','A',1);
insert into question values(528,7,99,'科学发展观的根本方法是 ()。','A',1);
insert into question values(529,7,100,' ()是中国特色社会主义的本质属性。','D',1);
insert into question values(530,7,101,' ()是中国特色社会主义的根本原则。','A',1);
insert into question values(531,7,102,'以 ()为中心是我们的兴国之要。','A',1);
insert into question values(532,7,103,'坚定理想信念，坚守共产党人精神追求,抓好() 是核心。','B',1);
insert into question values(533,7,104,'党的十八大报告提出，要加快形成 ()相结合的社会管理机制。','B',1);
insert into question values(534,7,105,'《中国共产党廉洁自律准则》对全体党员和各级党员领导干部提出了()的总要求。','B',1);
insert into question values(535,7,106,'《中国共产党廉洁自律准则》除导语外，还分为两部分：一是党员廉洁自律规范;二是()。','C',1);
insert into question values(536,7,107,'根据《中国共产党纪律处分条例》，对严重违犯党纪的党组织的纪律处理措施有：()','AC',1);
insert into question values(537,7,108,'《中国共产党廉洁自律准则》要求党员领导干部廉洁用权，()。','A',1);
insert into question values(538,7,109,'《中国共产党纪律处分条例》指出，()是最根本的党内法规，是管党治党的总规矩。','A',1);
insert into question values(539,7,110,'根据《中国共产党纪律处分条例》，党组织在纪律审查中发现党员有贪污贿赂、失职渎职等刑法规定的行为涉嫌犯罪的，应当给予()处分。','BCD',1);
insert into question values(540,7,111,'《中国共产党廉洁自律准则》要求党员领导干部()，自觉保持人民公仆本色。','B',1);
insert into question values(541,7,112,'《中国共产党纪律处分条例》规定，党的各级代表大会的代表受到()处分的，党组织应当终止其代表资格。','C',1);
insert into question values(542,7,113,'根据《行政机关公务员处分条例》，解除降级、撤职处分，()。','A',1);
insert into question values(543,7,114,'马克思列宁主义揭示了（），它的基本原理是正确的，具有强大的生命力。','C',1);
insert into question values(544,7,115,'毛泽东思想是马克思列宁主义在中国的运用和发展，是被实践证明了的关于（）的正确的理论原则和经验总结，是中国共产党集体智慧的结晶。','A',1);
insert into question values(545,7,116,'邓小平理论是马克思列宁主义的基本原理同当代中国实践和时代特征相结合的产物，是毛泽东思想在新的历史条件下的继承和发展，是马克思主义在中国发展的新阶段，是（），是中国共产党集体智慧的结晶，引导着我国社会主义现代化事业不断前进。','C',1);
insert into question values(546,7,117,'十三届四中全会以来，以江泽民同志为主要代表的中国共产党人，在建设中国特色社会主义的实践中，加深了对什么是社会主义、怎样建设社会主义和建设什么样的党、怎样建设党的认识，积累了治党治国新的宝贵经验，形成了（）。','C',1);
insert into question values(547,7,118,'“三个代表”重要思想是对马克思列宁主义、毛泽东思想、邓小平理论的继承和发展，反映了当代世界和中国的发展变化对党和国家工作的新要求，是加强和改进党的建设，推进（）的强大理论武器，是中国共产党集体智慧的结晶，是党必须长期坚持的指导思想。','A',1);
insert into question values(548,7,119,'始终做到“三个代表’，是我们党的立党之本、执政之基、（）。','B',1);
insert into question values(549,7,120,'我国正处于并将长期处于（）。这是在经济文化落后的中国建设社会主义现代化不可逾越的历史阶段，需要上百年的时间。','B',1);
insert into question values(550,7,121,'中国共产党在社会主义初级阶段的（）是：领导和团结全国各族人民，以经济建设为中心，坚持四项基本原则，坚持改革开放，自力更生，艰苦创业，为把我国建设成为富强、民主、文明的社会主义现代化国家而奋斗。','A',1);
insert into question values(551,7,122,'中国共产党在领导社会主义事业中，必须坚持以经济建设为中心，其他各项工作都服从和服务于这个中心。要抓紧时机，加快发展，实施科教兴国战略、人才强国战略和（），充分发挥科学技术作为第一生产力的作用，依靠科技进步，提高劳动者素质，做到效益好、质量高、速度快，努力把经济建设搞上去。','B',1);
insert into question values(552,7,123,'党的领导主要是（）的领导。','B',1);
insert into question values(553,7,124,'党的思想路线是一切从实际出发，理论联系实际，（），在实践中检验真理和发展真理。','A',1);
insert into question values(554,7,125,'民主集中制是民主基础上的集中和集中指导下的民主相结合。它既是党的（），也是群众路线在党的生活中的运用。','C',1);
insert into question values(555,7,126,'我们党的最大政治优势是（），党执政后的最大危险是脱离群众。','A',1);
insert into question values(556,7,127,'在现阶段，我国社会的（）是人民日益增长的物质文化需要同落后的社会生产之间的矛盾。','C',1);
insert into question values(557,7,128,'必须尊重劳动、尊重知识、尊重人才、（），做到发展为了人民、发展依靠人民、发展成果由人民共享。','C',1);
insert into question values(558,7,129,'跨入新世纪，我国进入（）的新的发展阶段。必须按照中国特色社会主义事业总体布局，全面推进经济建设、政治建设、文化建设、社会建设、生态文明建设。','C',1);
insert into question values(559,7,130,'党员必须自觉遵守党的纪律，模范遵守（），严格保守党和国家的秘密，执行党的决定，服从组织分配，积极完成党的任务。','B',1);
insert into question values(560,7,131,'预备党员的（）同正式党员一样。','C',1);
insert into question values(561,7,132,'党员如果没有正当理由，连续（）不参加党的组织生活，或不交纳党费，或不做党所分配的工作，就被认为是自行脱党。','B',1);
insert into question values(562,7,133,'党是根据自己的（），按照民主集中制组织起来的统一整体。','C',1);
insert into question values(563,7,134,'党的最高领导机关，是（）和它所产生的中央委员会。','A',1);
insert into question values(564,7,135,'党的各级委员会实行集体领导和个人分工负责相结合的制度。凡属重大问题都要按照集体领导、民主集中、（）、会议决定的原则，由党的委员会集体讨论，作出决定。','A',1);
insert into question values(565,7,136,'党的各级代表大会的代表和委员会的产生，要体现（）的意志。选举采用无记名投票的方式。候选人名单要由党组织和选举人充分酝酿讨论。','B',1);
insert into question values(566,7,137,'凡是成立党的新组织，或是撤销党的原有组织，必须由（）决定。','A',1);
insert into question values(567,7,138,'企业、农村、机关、学校、科研院所、街道社区、社会团体、社会中介组织、人民解放军连队和其他基层单位，凡是有正式党员（），都应当成立党的基层组织。','A',1);
insert into question values(568,7,139,'党的基层组织是党在社会基层组织中的（），是党的全部工作和战斗力的基础。','B',1);
insert into question values(569,7,140,'街道、乡、镇党的基层委员会和村、社区党组织，领导本地区的工作，（）行政组织、经济组织和群众自治组织充分行使职权。','C',1);
insert into question values(570,7,141,'国有企业和集体企业中党的基层组织，发挥（）作用围绕企业生产经营开展工作。','A',1);
insert into question values(571,7,142,'非公有制经济组织中党的基层组织，贯彻党的方针政策，（）企业遵守四家的法律法规，领导工会、共青团等群众组织，团结凝聚职工群众，维护各方的合法权益，促进企业健康发展。','A',1);
insert into question values(572,7,143,'党的干部是党的事业的骨干，是人民的公仆。党按照德才兼备的原则选拔干部，坚持任人唯贤，反对任人唯亲，努力实现干部队伍的（）、年轻化、知识化、专业化。','B',1);
insert into question values(573,7,144,'党重视教育、培训、选拔和考核干部，特别是培养、选拔优秀（）。积极推进干部制度改革。','B',1);
insert into question values(574,7,145,'党章规定的共产党员必须履行的第一项义务是：认真学习马克思列宁主义、毛泽东思想、邓小平理论和（），学习党的路线、方针、政策和决议，学习党的基本知识，学习科学、文化、法律和业务知识，努力提高为人民服务的本领。','B',1);
insert into question values(575,7,146,'预备党员认真履行党员义务，具备党员条件的，应当按期转为正式党员;需要继续考察和教育的，可以延长预备期，但不能超过（）。','B',1);
insert into question values(576,7,147,'党员个人服从（），少数服从多数，下级组织服从上级组织，全党各个组织和全体党员服从党的全国代表大会和中央委员会，这是党的民主集中制的基本原则之一。','A',1);
insert into question values(577,7,148,'党的全国代表大会每五年举行一次，由中央委员会召集。中央委员会认为有必要，或者有（）以上的省一级组织提出要求，全国代表大会可以提前举行;如无非常情况，不得延期举行。','B',1);
insert into question values(578,7,149,'党的基层委员会每届任期三年至五年，总支部委员会、支部委员会每届任期（）。','C',1);
insert into question values(579,7,150,'党的干部必须正确行使人民赋予的权力，依法办事，清正廉洁，勤政为民，以身作则，艰苦朴素，密切联系群众，坚持党的群众路线，自觉地接受党和群众的批评和监督，做到自重、（）、自警、自励，反对官僚主义，反对任何滥用职权、谋求私利的不正之风。','C',1);
insert into question values(580,7,151,'《中国共产党廉洁自律准则》对全体党员和各级党员领导干部提出了﹍﹍﹍的总要求。（         ）','B',1);
insert into question values(581,7,152,'《中国共产党廉洁自律准则》除导语外，还分为两部分：一是党员廉洁自律规范；二是﹍﹍﹍。 （         ）','C',1);
insert into question values(582,7,153,'《中国共产党廉洁自律准则》要求党员领导干部﹍﹍﹍，自觉保持人民公仆本色。（         ）','B',1);
insert into question values(583,7,154,'《中国共产党廉洁自律准则》要求党员领导干部廉洁用权，﹍﹍。（       ）','A',1);
insert into question values(584,7,155,'《中国共产党纪律处分条例》规定，党员受到严重警告处分的，﹍﹍﹍内不得在党内提升职务和向党外组织推荐担任高于其原任职务的党外职务。（         ）','B',1);
insert into question values(585,7,156,'《中国共产党纪律处分条例》规定，党的各级代表大会的代表受到﹍﹍﹍处分的，党组织应当终止其代表资格。（         ）','C',1);
insert into question values(586,7,157,'《中国共产党纪律处分条例》规定，受到留党察看处分的党员，在恢复党员权利后﹍﹍﹍内，不得在党内担任和向党外组织推荐担任与其原任职务相当或者高于其原任职务的职务。（        ）','C',1);
insert into question values(587,7,158,'《中国共产党纪律处分条例》规定，党纪处分决定作出后，应当在﹍﹍﹍内向受处分党员所在党的基层组织中的全体党员及其本人宣布。（     ）','A',1);
insert into question values(588,7,159,'《中国共产党纪律处分条例》规定，在党内搞团团伙伙、结党营私、拉帮结派、培植私人势力或者通过搞利益交换、为自己营造声势等活动捞取政治资本的行为，违反了党的﹍﹍﹍。（         ）','A',1);
insert into question values(589,7,160,'《中国共产党纪律处分条例》规定，违反个人有关事项报告规定，不报告、不如实报告的行为，违反了党的﹍﹍﹍。（         ）','B',1);
insert into question values(590,7,161,'《中国共产党纪律处分条例》规定，党员领导干部用公款旅游、借公务差旅之机旅游或者以公务差旅为名变相旅游的行为，违反了党﹍﹍﹍。（         ）','D',1);
insert into question values(591,7,162,'《行政机关公务员处分条例》规定，对行政机关公务员的处分种类包括﹍﹍﹍﹍﹍﹍六种。（         ）','C',1);
insert into question values(592,7,163,'《行政机关公务员处分条例》规定，对地方各级人民代表大会及其常务委员会选举或者决定任命的地方各级人民政府领导人员给予处分，由 ﹍﹍﹍人民政府决定。（        ）','B',1);
insert into question values(593,7,164,'《行政机关公务员处分条例》规定，行政机关公务员处分期最长不得超过﹍﹍﹍月。（         ）','C',1);
insert into question values(594,7,165,'《行政机关公务员处分条例》规定，行政机关公务员受处分的期间为：﹍﹍﹍。 （         ）','D',1);
insert into question values(595,7,166,'《行政机关公务员处分条例》规定，对地方各级人民政府工作部门正职领导人员给予处分，由﹍﹍﹍决定。（         ）','A',1);
insert into question values(596,7,167,'根据《行政机关公务员处分条例》，解除降级、撤职处分，﹍﹍。（       ）','A',1);
insert into question values(597,7,168,'2015年修订的《中国共产党廉洁自律准则》和《中国共产党纪律处分条例》是对﹍﹍﹍﹍﹍﹍的具体化。（         ）','B',1);
insert into question values(598,7,169,'《中国共产党纪律处分条例》把党章对纪律的要求整合成政治纪律、组织纪律和廉洁纪律等、﹍﹍﹍大纪律、。 （         ）','B',1);
insert into question values(599,7,170,'《中国共产党纪律处分条例》规定，挑拨民族关系制造事端或者参加民族分裂活动的，对策划者、﹍﹍﹍﹍和骨干分子，给予开除党籍处分。 （         ）','C',1);
insert into question values(600,7,171,'《党政机关办公用房建设标准》中规定省级机关正厅级领导干部办公用房的使用面积为﹍﹍﹍﹍平方米/人。（         ）','D',1);
insert into question values(601,7,172,'《党政机关国内公务接待管理规定》规定，接待对象应当按照规定标准自行用餐。确因工作需要，接待单位可以安排工作餐一次，并严格控制陪餐人数。接待对象在10人以内的，陪餐人数不得超过﹍﹍﹍﹍人；超过10人的，不得超过接待对象人数的三分之一。（         ）','A',1);
insert into question values(602,7,173,'《中国共产党纪律处分条例》规定，党员受到开除党籍处分，﹍﹍﹍年内不得重新入党，另有规定不准重新入党的，依照规定。（    ）','D',1);
insert into question values(603,7,174,'《中国共产党廉洁自律准则》要求党员领导干部﹍﹍﹍，自觉带头树立良好家风。（    ）','B',1);
insert into question values(604,7,175,'根据《中国共产党纪律处分条例》，实施党纪处分,应当按照规定程序经党组织集体讨论决定,不允许任何个人或者少数人决定和批准。上级党组织对违犯党纪的党组织和党员作出的处理决定,下级党组织必须执行。以上表述概括的是下列那一项原则？(    )','D',1);
insert into question values(605,7,176,'《中国共产党纪律处分条例》规定，篡改、伪造个人档案资料的，给予严重警告处分；情节严重的，给予﹍﹍﹍处分。（    ）','C',1);
insert into question values(606,7,177,'《中国共产党纪律处分条例》规定，违反公务接待管理规定，超标准、超范围接待或者借机大吃大喝，对直接责任者和领导责任者，情节较重的，给予警告或者严重警告处分；情节严重的，给予﹍﹍﹍处分。（   ）','C',1);
insert into question values(607,7,178,'根据《中国共产党纪律处分条例》，在特殊时期或者紧急状况下，拒不执行党组织决定的，给予﹍﹍﹍。（    ）','D',1);
insert into question values(608,7,179,'《中国共产党纪律处分条例》规定，生活奢靡、贪图享乐、追求低级趣味，造成不良影响的，给予警告或者严重警告处分；情节严重的，给予﹍﹍﹍处分。（   ）','C',1);
insert into question values(609,7,180,'《中国共产党纪律处分条例》规定，对党员的纪律处分种类有：警告；﹍﹍﹍；撤销党内职务；留党察看；开除党籍。（    ）','B',1);
insert into question values(610,7,181,'习近平总书记在十八届中央纪委六次全会上强调，全面从严治党，核心是加强党的领导，﹍﹍﹍﹍﹍。（      ）','A',1);
insert into question values(611,7,182,'习近平总书记在十八届中央纪委五次全会上强调，﹍﹍﹍﹍﹍是成文的规矩，一些未明文列入纪律的规矩是不成文的纪律；﹍﹍﹍﹍﹍是刚性的规矩，一些未明文列入纪律的规矩是自我约束的纪律。（      ）','C',1);
insert into question values(612,7,183,'王岐山同志在十八届中央纪委五次全会上强调，坚持、一案双查、，对违反党的政治纪律和政治规矩、组织纪律，、四风、问题突出、发生顶风违纪问题，出现区域性、系统性腐败案件的地方、部门和单位，既追究﹍﹍﹍﹍﹍、﹍﹍﹍﹍﹍，又严肃追究领导责任。（      ）','C',1);
insert into question values(613,7,184,'习近平总书记在十八届中央纪委五次全会上强调，﹍﹍﹍﹍﹍是全党必须遵循的总章程，也是总规矩。（      ）','A',1);
insert into question values(614,7,185,'习近平总书记在十八届中央纪委五次全会上强调，国家法律是党员、干部必须遵守的规矩，﹍﹍﹍是党领导人民制定的，全党必须模范执行。（    ）','A',1);
insert into question values(615,7,186,'十八届中央纪委五次全会强调,纠正、四风、重点查处﹍﹍﹍﹍﹍，中央八项规定出台后，群众路线教育实践活动开展后仍顶风违纪的行为。（      ）','C',1);
insert into question values(616,7,187,'习近平总书记在十八届中央纪委六次全会上指出，领导干部要把﹍﹍﹍﹍﹍摆在重要位置，廉洁修身、廉洁齐家。（      ）','D',1);
insert into question values(617,7,188,'王岐山同志在十八届中央纪委六次全会上强调，紧盯年节假期、一个节点一个节点坚守，坚持以上率下、看住﹍﹍﹍﹍﹍。（     ）','B',1);
insert into question values(618,7,189,' 王岐山同志在十八届中央纪委五次全会上强调，主体责任是党章赋予各级党组织的﹍﹍﹍﹍﹍。（      ）                                              、第一责任  、政治责任  、基本责任  、重要职责','CABD',1);
insert into question values(619,7,190,'习近平总书记在十八届中央纪委二次全会上强调，中央八项规定既不是最高标准，更不是最终目的，只是我们改进作风的第一步，是我们作为共产党人应该做到的﹍﹍﹍﹍﹍。（      ）　　','A',1);
insert into question values(620,7,191,'习近平总书记在十八届中央纪委二次全会上指出，改进工作作风，就是要净化﹍﹍﹍﹍﹍，营造廉洁从政的良好环境。（      ）','A',1);
insert into question values(621,7,192,'严明纪律不能时紧时松，要体现在﹍﹍﹍﹍﹍中，每日每时都要做，有病就要及时治，这才是对干部的真正爱护，对党纪的切实维护。（      ）','A',1);
insert into question values(622,7,193,'关于党风与民风社风的关系，﹍﹍﹍﹍﹍说法不正确。（      ）','B',1);
insert into question values(623,7,194,'党规党纪严于国家法律，这是由中国共产党的﹍﹍﹍﹍﹍决定的。党只有以更严的标准、更严的纪律要求和约束各级党组织和广大党员干部，才能永葆先进性和纯洁性。（      ）','A',1);
insert into question values(624,7,195,'我们党治国理政的重要理念是﹍﹍﹍﹍﹍相结合，是社会主义法治的鲜明特色，这是由中华民族的文化基因决定的。（      ）','C',1);
insert into question values(625,7,196,'党的建设要与时俱进、创新发展。把纪律挺在前面，实现标本兼治，必须在﹍﹍﹍﹍﹍上不断创新。（      ）','A',1);
insert into question values(626,7,197,'在党的所有纪律中，﹍﹍﹍﹍﹍排在第一位。不管违反哪方面的纪律，发展到一定程度，都会在群众中和党内造成恶劣影响，最终都会侵蚀党的执政基础。（      ）','A',1);
insert into question values(627,7,198,'全心全意为人民服务是党的根本宗旨，密切联系群众是党的优良传统和最大政治优势。新形势下，党面临的最大危险，就是﹍﹍﹍﹍﹍的危险，这直接关乎人心向背、关乎党的执政基础。（      ）','C',1);
insert into question values(628,7,199,'加强﹍﹍﹍﹍﹍是全面从严治党的治本之策。（      ）','A',1);
insert into question values(629,7,200,'政党是讲政治的组织，﹍﹍﹍﹍是任何政党对其党员的政治要求。（    ）','B',1);
insert into question values(630,7,201,'党的十八大报告指出:回首历史，展望未来，我们得出一个坚定的结论：全面建成小康社会，加快推进社会主义现代化，实现中华民族伟大复兴，必须坚定不移走﹍﹍﹍道路。(   )','A',1);
insert into question values(631,7,202,'党的十八大报告提出：必须更加自觉地把全面协调可持续作为深入贯彻落实科学发展观的基本要求，全面落实﹍﹍五位一体总体布。（   ）','D',1);
insert into question values(632,7,203,'2015年5月习近平总书记在浙江调研时强调，干在实处永无止境，走在前列要谋新篇。协调推进﹍﹍﹍﹍﹍﹍﹍进程，切实解决改革发展中的突出矛盾和问题，努力实现经济社会持续健康发展。( )','A',1);
insert into question values(633,7,204,'党的十八届四中全会《决定》将每年﹍﹍﹍﹍定为国家宪法日。在全社会普遍开展宪法教育，弘扬宪法精神。（   ）','D',1);
insert into question values(634,7,205,'2015年6月，习近平总书记在贵州召开部分省区市党委主要负责同志座谈会时，就加大力度推进扶贫开发工作提出了，切实落实领导责任，切实做到﹍﹍﹍﹍，切实强化社会合力，切实加强基层组织的要求。（   ）','A',1);
insert into question values(635,7,206,'习近平总书记在十八届中央政治局第五次集体学习时的讲话强调，中央提出抓作风建设，反对形式主义、官僚主义、享乐主义，反对奢靡之风，就是提出了一个抓﹍﹍﹍﹍﹍﹍﹍的着力点，提出了一个夯实党执政的群众基础的切入点。（   ）','C',1);
insert into question values(636,7,207,'2015年10月习近平总书记在十八届中央政治局常委会第一百一十九次会议关于审议中国共产党廉政准则、党纪处分条例修订稿时的讲话提出，办好中国的事情，关键在党。全面从严治党，核心是加强﹍﹍﹍。（    ）','A',1);
insert into question values(637,7,208,'2015年10月习近平总书记在十八届中央政治局常委会第一百一十九次会议关于审议中国共产党廉政准则、党纪处分条例修订稿时的讲话提出，加强﹍﹍﹍是全面从严治党的治本之策。（    ）','C',1);
insert into question values(638,7,209,'2014年5月习近平总书记在参加河南省兰考县委常委班子专题民主生活会时的讲话提出，要坚持按﹍﹍﹍原则处理党内组织和组织、组织和个人、同志和同志、集体领导和个人分工负责等重要关系，发扬党内民主、增进党内和谐，实行正确集中、维护党的团结统一。（   ）','C',1);
insert into question values(639,7,210,'2015年6月习近平总书记在十八届中央政治局第二十四次集体学习时的讲话提出，、善除害者察其本，善理疾者绝其源。、铲除不良作风和腐败现象滋生蔓延的土壤，根本上要靠﹍﹍﹍。（    ）','C',1);
insert into question values(640,7,211,'2014年10月习近平总书记在党的群众路线教育实践活动总结大会上的讲话指出，一个班子强不强、有没有战斗力，同有没有严肃认真的﹍﹍﹍密切相关。（   ）','A',1);
insert into question values(641,7,212,'习近平总书记指出，要把学习弘扬焦裕禄精神作为一条红线贯穿教育实践活动始终，做到﹍﹍﹍。（   ）','C',1);
insert into question values(642,7,213,'被习近平总书记称为共产党人精神上的、钙、的是﹍﹍﹍。（   ）','B',1);
insert into question values(643,7,214,'十八大指出，科学发展观最鲜明的精神实质是﹍﹍﹍。 （   ）','C',1);
insert into question values(644,7,215,'十八大指出，建设中国特色社会主义，关于中国特色社会主义的总布局是﹍﹍﹍。（    ）','A',1);
insert into question values(645,7,216,' 党的十八大报告指出，反对腐败、建设﹍﹍﹍，是党一贯坚持的鲜明政治立场，是人民关注的重大政治问题。（   ）','A',1);
insert into question values(646,7,217,'党的十八大报告指出，不断提高党的领导水平和执政水平、提高﹍﹍﹍能力，是党巩固执政地位、实现执政使命必须解决好的重大课题。（  ）','C',1);
insert into question values(647,7,218,'党的十八大报告指出，要全面加强党的思想建设、组织建设、作风建设、反腐倡廉建设、制度建设，增强﹍﹍﹍、自我完善、自我革新、自我提高能力。','',1);
insert into question values(648,7,219,'党的十八大报告指出，建设中国特色社会主义，总依据是社会主义初级阶段，总布局是五位一体，总任务是﹍﹍﹍。（   ）','C',1);
insert into question values(649,7,220,'群众路线教育实践活动以﹍﹍﹍为总要求。（ ）','C',1);
insert into question values(650,7,221,'十八届三中全会指出，全面深化改革的总目标是﹍﹍﹍。（   ）','A',1);
insert into question values(651,7,222,'十八届五中全会指出，、十三五、时期是﹍﹍﹍决胜阶段，、十三五、规划必须紧紧围绕实现这个奋斗目标来制定。 （   ）','B',1);
insert into question values(652,7,223,'十八届五中全会提出,实现、十三五、时期发展目标，破解发展难题，厚植发展优势，必须牢固树立并切实贯彻﹍﹍﹍的发展理念。 （   ）','A',1);
insert into question values(653,7,224,'十八届五中全会提出,坚持创新发展，必须把创新摆在国家发展全局的核心位置，不断推进﹍﹍﹍等各方面创新，让创新贯穿党和国家一切工作，让创新在全社会蔚然成风。（   ）','A',1);
insert into question values(654,7,225,'十八届五中全会提出,坚持共享发展，必须坚持发展为了人民、发展依靠人民、发展成果由人民共享，作出更有效的制度安排，使全体人民在共建共享发展中有更多﹍﹍﹍。 （   ）','A',1);
insert into question values(655,7,226,'《中国共产党党组工作条例（试行）》规定，党组成员除应当具备党章和《党政领导干部选拔任用工作条例》规定的党员领导干部的基本条件外，还应当有﹍﹍﹍党龄，其中厅局级以上单位的党组成员应当有﹍﹍﹍党龄。（  ）','D',1);
insert into question values(656,7,227,'《中国共产党党组工作条例（试行）》规定，党组会议应当有﹍﹍﹍党组成员到会方可召开，讨论决定干部任免事项必须有﹍﹍﹍党组成员到会。（  ）','D',1);
insert into question values(657,7,228,'《中国共产党巡视工作条例》规定，﹍﹍有义务向巡视组如实反映情况。（ ）','C',1);
insert into question values(658,7,229,'《党政领导干部选拔任用工作条例》规定，选拔任用党政领导干部，应当按照干部管理权限由﹍﹍﹍集体讨论作出任免决定，或者决定提出推荐、提名的意见。属于上级党委（党组）管理的，本级党委（党组）可以提出选拔任用建议。（    ）','D',1);
insert into question values(659,7,230,'《党政领导干部选拔任用工作条例》规定，党委（党组）讨论决定干部任免事项，必须有﹍﹍﹍以上成员到会，并保证与会成员有足够时间听取情况介绍、充分发表意见。与会成员对任免事项，应当发表同意、不同意或者缓议等明确意见。（    ）','B',1);
insert into question values(660,0,12,'党的十八届五中全会提出“十三五”时期我国发展的指导思想的战略布局是（   ）','ABCD',2);
insert into question values(661,0,13,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》指出全面深化改革的总目标是完善和发展中国特色社会主义制度，推进国家治理体系和治理能力现代化，必须更加注重改革的()','ABC',2);
insert into question values(662,0,14,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》指出指出，全面深化改革的总目标是完善和发展中国特色社会主义制度，推进国家治理体系和治理能力现代化。必须更加注重改革的系统性、整体性、协同性，加快发展社会主义市场经济、民主政治、先进文化、和谐社会、生态文明，让一切劳动、知识、技术、管理、资本的活力竞相迸发，让()','BCD',2);
insert into question values(663,0,15,' 2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》指出，改革开放的成功实践为全面深化改革提供了重要的经验，必须长期坚持。最重要的是，坚持()','ABCD',2);
insert into question values(664,0,16,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》提出，公有制为主体、多种所有制经济共同发展的基本经济制度，是()','AB',2);
insert into question values(665,0,17,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》提出，公有制经济和非公有制经济都是社会主义市场经济的重要组成部分，都是我国经济社会发展的重要基础。必须()','ABCD',2);
insert into question values(666,0,18,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》提出，科学的宏观调控，有效的政府治理，是发挥社会主义市场经济体制优势的内在要求。必须()','ABCD',2);
insert into question values(667,0,19,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》提出，城乡二元结构是制约城乡发展一体化的主要障碍。必须健全体制机制，形成新型工业城乡关系是()','ABCD',2);
insert into question values(668,0,20,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》提出，适应经济全球化新形势，构建开放型经济新体制必须()','ABCD',2);
insert into question values(669,0,21,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》提出，建设社会主义文化强国，增强国家文化软实力，必须坚持()','ABCD',2);
insert into question values(670,0,22,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》提出，实现发展成果更多更公平惠及全体人民，必须加快社会事业改革，解决好人民最关心最直接最现实的利益问题，更好满足人民需求。要()','ABCD',2);
insert into question values(671,0,23,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》提出，建设生态文明，必须建立系统完整的生态文明制度体制，用制度保护生态环境。要()','ABCD',2);
insert into question values(672,0,24,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》指出中央成立全面深化改革领导小组，负责改革()','ABCD',2);
insert into question values(673,0,25,'2013年11月12日，中共十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》指出全会高度评价党的十一届三中全会召开35年来改革开放的成功实践和伟大成就，研究了全面深化改革若干重大问题，认为改革开放是()','ABCD',2);
insert into question values(674,1,119,'中国革命、建设和改革的证明，马克思主义之所以能在中国发挥指导作用，是因为（    ）','ABCD',2);
insert into question values(675,1,120,'把马克思主义的基本原理更进一步地同（     ）结合起来，使马克思主义在中国实现具体化','ABC',2);
insert into question values(676,1,121,'在当代中国，马克思主义中国化就是要把马克思主义的基本原理同中国社会主义现代化建设的实践经验很好地结合起来，（    ）','AB',2);
insert into question values(677,1,122,'马克思主义中国化（    ），而是将马克思主义的基本原理同中国文化中的优秀成分结合进而达到融合','AB',2);
insert into question values(678,1,123,'马克思主义中国化就是用马克思主义来解决中国的问题，同时又使中国丰富的实践经验上升为理论，并且同中国的历史传统、中国的优秀文化相结合，不断赋予中国马克思主义以鲜明的（   ）','ACD',2);
insert into question values(679,1,124,'党在幼年时期，由于理论准备和实践经验都不足，（    ），使中国革命走了一些弯路，出现了严重的曲折。','BCD',2);
insert into question values(680,1,125,'中国共产党在领导中国革命、建设和改革的长期实践中，实现了马克思主义同中国实际相结合的两次历史性飞跃，产生了两大理论成果，它们是（    ）','AD',2);
insert into question values(681,1,126,'马克思主义中国化的一系列理论成果，代表着中国最广大人民在不同历史时期的意志和愿望，（    ）','ABC',2);
insert into question values(682,1,127,'新时期以来我们取得的一切成绩和进步的根本原因，归结起来就是：（    ）','AC',2);
insert into question values(683,1,128,'改革开放30年来，中国共产党的全部理论和全部实践，归结起来就是创造性地探索和回答了（   ）等重大理论和实践问题','ABCD',2);
insert into question values(684,1,129,'党的十七大报告指出：中国特色社会主义伟大旗帜，是（    ）','CD',2);
insert into question values(685,1,130,'高举中国特色社会主义旗帜，是（   ）','ABC',2);
insert into question values(686,1,131,'中国特色社会主义道路之所以完全正确、之所以能引领中国发展进步，关键在于（   ）','AB',2);
insert into question values(687,1,132,'党的十七大对改革开放30年来马克思主义中国化理论成果做出最新概括，指出：中国特色社会主义理论体系，就是包括（     ）等重大战略思想在内的科学理论体系','BCD',2);
insert into question values(688,1,133,'中国特色社会主义理论体系坚持和发展了马克思列宁主义、毛泽东思想，凝结了几代中国共产党人带领人民不断探索实践的智慧和心血，是（   ）','ACD',2);
insert into question values(689,1,134,'中国特色社会主义理论体系作为马克思主义中国化的最新成果，是对（    ）的继承发展','ABD',2);
insert into question values(690,1,135,'毛泽东思想的科学含义是（   ）','ABC',2);
insert into question values(691,1,136,'毛泽东指出：（   ）是中国共产党在中国革命中战胜敌人的三个主要的法宝','ABD',2);
insert into question values(692,1,137,'毛泽东思想的活的灵魂，是贯穿于各个理论的立场、观点和方法。它们有三个基本方面，即（    ）','ABC',2);
insert into question values(693,1,138,'邓小平强调改革（     ），僵化停滞是没有出路的','BCD',2);
insert into question values(694,1,139,'始终作到“三个代表”，是我们党的（   ）','ABD',2);
insert into question values(695,1,140,'中国共产党必须始终（   ），这是对“三个代表”重要思想的集中概括','BCD',2);
insert into question values(696,1,141,'始终代表中国先进生产力的发展要求，就是党的理论、路线、纲领、方针、政策和各项工作，（    ），通过发展生产力不断提高人民群众的生活水平','ABD',2);
insert into question values(697,1,142,'始终代表中国先进文化的前进方向，就是党的理论、路线、纲领、方针、政策和各项工作，必须努力体现（    ），民族的科学的大众的社会主义文化的要求，促进全民族思想道德素质和科学文化素质的不断提高，为我国经济发展和社会进步提供精神动力和智力支持','BCD',2);
insert into question values(698,1,143,'“三个代表”重要思想的形成，表明党对（   ）的认识，达到了新的理论高度','ACD',2);
insert into question values(699,1,144,'科学发展观，是（   ）提出来的','ABCD',2);
insert into question values(700,1,145,'以下关于中国化马克思主义的基本内涵的表述中不正确的是（   ）','ABCD',2);
insert into question values(701,1,146,'邓小平理论是（    ）','ABC',2);
insert into question values(702,1,147,'先后对毛泽东思想的科学含义做出概括的文献是（    ）','BC',2);
insert into question values(703,1,148,'关于毛泽东思想正确的说法有（     ）','AB',2);
insert into question values(704,1,149,'科学发展观的历史地位在于（    ）','ABCD',2);
insert into question values(705,1,150,'十八大报告提出：根据我国经济社会发展实际，要在十六大、十七大确立的全面建设小康社会目标的基础上努力实现新的要求。这些新要求是（）','ABCDE',2);
insert into question values(706,1,151,'十八大报告指出，总结十年奋斗历程最重要的是形成和贯彻了科学发展观，科学发展观的重要意义在于（）','ABCD',2);
insert into question values(707,1,152,'推动经济社会发展是科学发展观的第一要义，概括而言，发展是指（ ）','ABC',2);
insert into question values(708,1,153,'十八大报告指出，科学发展观的最为鲜明的精神实质是（）','ABCD',2);
insert into question values(709,1,154,'十八大报告指出，高举中国特色社会主义伟大旗帜要坚决反对的主要错误倾向是（）','AB',2);
insert into question values(710,1,155,'中国共产党面向未来的“两个一百年”是（  ）','AB',2);
insert into question values(711,1,156,'十八大提出，从2010年到2020年要实现“两个倍增”计划是（  ）','AD',2);
insert into question values(712,1,157,'思想路线亦称认识路线，是指人们的认识所遵循的（    ）','ABCD',2);
insert into question values(713,1,158,'党的思想路线的基本内容是（ 　）','ABE',2);
insert into question values(714,1,159,'党的实事求是思想路线的基本要求是（    ）','ABCDE',2);
insert into question values(715,1,160,'毛泽东深刻阐述理论对于实践的依赖关系，以及矛盾的普遍性和特殊性关系，对党的思想路线作出系统的哲学认证的著作是（     ）','BC',2);
insert into question values(716,1,161,'经过（    ）和（    ），实事求是的思想路线在全党得到了确立。','BC',2);
insert into question values(717,1,162,'确立实事求是的思想路线对于中国革命和建设的重要意义是（   ）','ACDE',2);
insert into question values(718,1,163,'在党的十六大报告中，江泽民明确提出，坚持党的思想路线，解放思想，实事求是，与时俱进，是我们党（    ）和（    ）的决定性因素','AC',2);
insert into question values(719,1,164,'下列哪些观点是对实事求是思想路线的丰富和发展（     ）','ABD',2);
insert into question values(720,1,165,'实事求是是毛泽东思想的精髓，是因为(     )','BCD',2);
insert into question values(721,1,166,'“两个凡是”的危害在于(      )','ABCD',2);
insert into question values(722,1,167,'邓小平在真理标准讨论过程中，提出了(      )','ABC',2);
insert into question values(723,1,168,'邓小平在批判“两个凡是”错误观点时强调解放思想，他所说的解放思想是指（     ）','AB',2);
insert into question values(724,1,169,'解放思想和实事求是的关系是(      )','ABE',2);
insert into question values(725,1,170,'改革开放以来的我国政治生活中的两个“解放思想、实事求是的宣言书”是指(     )','AE',2);
insert into question values(726,1,171,'与时俱进就是党的全部理论和工作要(      )','ABC',2);
insert into question values(727,1,172,'坚持与时俱进必须自觉地把思想认识(      )','ABC',2);
insert into question values(728,1,173,'创新包括(      )','ABCDE',2);
insert into question values(729,1,174,'坚持一切从实际出发，就要（   ）','ABCD',2);
insert into question values(730,1,175,'坚持一切从实际出发，就要把现象当作入门的向导，通过（    ）的科学分析，揭示事物的本质。','BCDE',2);
insert into question values(731,1,176,'在理论与实际的关系上，中国共产党在历史上曾经出现过的错误倾向有（    ）','ABE',2);
insert into question values(732,1,177,'要做到理论联系实际，必须（   ）','ABCDE',2);
insert into question values(733,1,178,'实事求是内在地包含着以下内容（    ）','ABCDE',2);
insert into question values(734,1,179,'党的全部理论和工作的与时俱进，要特别重视理论创新。实现理论创新，必须自觉地做到（   ）','ABCDE',2);
insert into question values(735,1,180,'实事求是思想路线具有重要的理论意义和实践意义，在于（    ）','ABCDE',2);
insert into question values(736,1,181,'与时俱进,就是党的全部理论和工作要(     )','ACE',2);
insert into question values(737,1,182,'坚持实事求是的思想路线,就要大力弘扬与时俱进精神,不断创新.创新包括(     )','ABCDE',2);
insert into question values(738,1,183,'坚持实事求是的思想路线,在中国革命.建设和改革问题上,要敢于和善于走自己的路. 走自己的路(     )','ABCDE',2);
insert into question values(739,1,184,'66．马克思主义的中国化，从理论创新方面讲，就是（    ）','ABC',2);
insert into question values(740,2,75,'中国新民主主义革命的动力包括（     ）','ABCD',2);
insert into question values(741,2,76,'中国共产党的新民主主义革命的三大经济纲领是（     ）','ABE',2);
insert into question values(742,2,77,'新民主主义社会的经济构成包括（     ）','ABCDE',2);
insert into question values(743,2,78,'新民主主义的文化是（     ）','BCDE',2);
insert into question values(744,2,79,'新民主主义革命的对象是（     ）','ABC',2);
insert into question values(745,2,80,'中国二大的历史功绩有（     ）','ABDE',2);
insert into question values(746,2,81,'中共四大提出的重要思想是（     ）','CD',2);
insert into question values(747,2,82,'中国半殖民地半封建的社会是一个“两头小中间大”的社会，两头小指的是(      )','CD',2);
insert into question values(748,2,83,'近代以来中华民族面对的两大历史任务，一个是求得民族独立和人民解放，一个是实现国家的繁荣富强和人民的共同富裕。这两大任务的相互关系是        (    )','BCDE',2);
insert into question values(749,2,84,'新旧民主主义革命的区别在于(    )','ABCD',2);
insert into question values(750,2,85,'新民主主义总路线包括的具体内容有(    )','ABCDE',2);
insert into question values(751,2,86,'中国革命的对象是(     )','ABC',2);
insert into question values(752,2,87,'中国革命之所以要反对官僚资本主义，是因为(    )','BCDE',2);
insert into question values(753,2,88,'毛泽东在新民主主义革命总路线中所说的“人民大众”，即革命动力是指(    )','ABCD',2);
insert into question values(754,2,89,'中国革命的基本问题是农民问题，这是由于(    )','ABCE',2);
insert into question values(755,2,90,'新民主主义革命必须由无产阶级领导(实质是共产党领导)，这是       (    )','ABCE',2);
insert into question values(756,2,91,'中国无产阶级除了具有世界无产阶级的一般特点外，还有许多特殊优点，有利于它在中国革命中成为领导阶级，这些特点是(     )','ABCD',2);
insert into question values(757,2,92,'中国共产党在中国革命中战胜敌人的三个法宝是(      )','ACE',2);
insert into question values(758,2,93,'在半殖民地半封建的中国，统一战线的主要力量是（    ）','ABCD',2);
insert into question values(759,2,94,'中国共产党在领导中国革命的进程中必须建立最广泛的统一战线的原因有','',2);
insert into question values(760,2,95,'抗日战争时期的抗日民族统一战线中包括（   ）','ABCDE',2);
insert into question values(761,2,96,'中国共产党制定的巩固和发展抗日民族统一战线的策略总方针包括（   ）','ABC',2);
insert into question values(762,2,97,'1945年毛泽东在《论联合政府》中指出，中国共产党区别于其他政党的显','',2);
insert into question values(763,2,98,'毛泽东在1928年至1930年发表的阐述农村包围城市、武装夺取政权革命道路理论的著作是(      )','ABCD',2);
insert into question values(764,2,99,'中国红色政权存在和发展的原因和条件是（    ）','ABCDE',2);
insert into question values(765,2,100,'土地革命战争时期，中国红色政权能够存在和发展的客观条件是      （    ）','ABE',2);
insert into question values(766,2,101,'中国革命的基本问题是农民问题，这是由于（   ）','ABCE',2);
insert into question values(767,2,102,'中国的武装斗争，实质上是无产阶级领导的以农民为主体的革命战争，这是','',2);
insert into question values(768,2,103,'农村包围城市理论的主要内容包括（   ）','ABC',2);
insert into question values(769,2,104,'“工农武装割据”思想的基本内容包括（   ）','ABCD',2);
insert into question values(770,2,105,'土地革命战争时期，中国红色政权能够存在和发展的主观条件是      （    ）','CE',2);
insert into question values(771,3,75,'中国从新民主主义向社会主义过渡的主要条件是（   ）','ABCDE',2);
insert into question values(772,3,76,'在中国进行社会主义改造的目的是（  ）','CDE',2);
insert into question values(773,3,77,'具有中国特色的社会主义改造道路的内容是（   ）','ABCE',2);
insert into question values(774,3,78,'1949年10月1日，中华人民共和国成立标志着（   ）','ACDE',2);
insert into question values(775,3,79,'中国共产党对农业实行社会主义改造的原则是（   ）','ACE',2);
insert into question values(776,3,80,'新中国成立初期的新民主主义经济成分有（    ）','ABCDE',2);
insert into question values(777,3,81,'过渡时期总路线的基本思想主要包括（   ）','BDE',2);
insert into question values(778,3,82,'中国民族资产阶级在社会主义改造时期的两面性表现为（    ）','CD',2);
insert into question values(779,3,83,'建国初期，中国共产党对民族资本主义经济所采取的政策是（    ）','ABE',2);
insert into question values(780,3,84,'对资本主义民族工商业实行保护政策的含义是（    ）','AC',2);
insert into question values(781,3,85,'低级的国家资本主义的形式包括（    ）','ABD',2);
insert into question values(782,3,86,'20世纪50年代初，我国对个体农业进行社会主义改造的成功经验有（    ）','ABE',2);
insert into question values(783,3,87,'虽然社会主义改造遗留了一些问题，但必须肯定的基本事实是，这场深刻的社会变革是在（    ）','ACE',2);
insert into question values(784,3,88,'在新民主主义社会中各种非社会主义因素是（    ）','ABCDE',2);
insert into question values(785,3,89,'对资本主义工商业的社会主义改造采取的形式是（    ）','ABCDE',2);
insert into question values(786,3,90,'中国共产党在探索中国建设道路过程中的理论成就有（    ）','ABC',2);
insert into question values(787,3,91,'在新民主主义社会中，存在多种经济成分，其中包括（  ）','ABCE',2);
insert into question values(788,3,92,'新民主主义时期我国基本的阶级力量包括（    ）','ABCE',2);
insert into question values(789,3,93,'我国的农业社会改造经历以下几个阶段（    ）','BCD',2);
insert into question values(790,3,94,'对于工人阶级和社会主义革命来说，民族资产阶级是（    ）','ABCD',2);
insert into question values(791,3,95,'在新民主主义社会的多种经济成分中，属于社会主义性质或半社会主义性质的经济成分是（    ）','AE',2);
insert into question values(792,3,96,'在新民主主义社会的多种经济成分中，主要的经济成分是（    ）','ABD',2);
insert into question values(793,3,97,'在新民主主义社会中，社会主义因素与资本主义因素之间不可避免地存在着（    ）','ABD',2);
insert into question values(794,3,98,'党在过渡时期的总路线简称为“一化三改”，下列答案中哪些是属于“一化三改”的正确内容（    ）','ABCE',2);
insert into question values(795,3,99,'历史证明，我国的社会主义改造是十分成功的，因为（    ）','ABDE',2);
insert into question values(796,3,100,'我国对资本主义工商业的社会主义改造之所以能采用和平赎买的方式，是因为（    ）','ABCDE',2);
insert into question values(797,3,101,'对资本主义工商业实行和平赎买，有利于（    ）','ABCDE',2);
insert into question values(798,3,102,'社会主义改造成功的历史经验包括（    ）','ABCD',2);
insert into question values(799,3,103,'在我国确立社会主义基本制度具有十分重大的意义，因为社会主义制度的确立（    ）','ABCDE',2);
insert into question values(800,3,104,'我国的社会主义改造也有一些失误和偏差。主要是（ ）','ABCDE',2);
insert into question values(801,4,42,'我国社会主义四个现代化是（    ）','ABCE',2);
insert into question values(802,4,43,'《论十大关系》是毛泽东关于社会主义建设的重要讲话，其中提出了要正确处理（    ）','ABCD',2);
insert into question values(803,4,44,'毛泽东作的《关于正确处理人民内部矛盾的问题》的讲话中，提出了（   ）','ABCD',2);
insert into question values(804,4,45,'在社会主义改造基本完成以后，由于对迅速到来的新生社会主义社会和全国规模的社会主义建设事业缺乏充分的思想准备和科学研究，对建设社会主义的客观规律缺乏深刻的认识，导致党在指导思想上发生了“左”的偏差，这些“左”的偏差的具体表现包括（    ）','ABCDE',2);
insert into question values(805,4,46,'毛泽东在总结“大跃进”以来我国社会主义建设的经验教训时，提出（   ）','ABCDE',2);
insert into question values(806,4,47,'在探索我国社会主义的发展阶段时，毛泽东提出社会主义可以分为（    ）','CD',2);
insert into question values(807,4,48,'我国社会主义制度建立以后，毛泽东从世界范围内两种社会制度的根本对立与斗争的角度，提出了要（    ）','ACD',2);
insert into question values(808,4,49,'改革开放前我国社会主义建设的经验教训主要有（  ）','ABCD',2);
insert into question values(809,4,50,'毛泽东指出，敌我矛盾和人民内部矛盾的性质和解决方法分别是（    ）','BC',2);
insert into question values(810,4,51,'毛泽东指出，用民主的方法解决人民内部矛盾，所谓民主方法是指（    ）','ADE',2);
insert into question values(811,4,52,'针对人民内部矛盾在具体实践中的不同情况，毛泽东提出了一系列具体方针，下面哪些是正确的（  ）','ABD',2);
insert into question values(812,4,53,'在《论十大关系》中，毛泽东讨论了哪些关于经济问题的关系(     )','ABCDE',2);
insert into question values(813,4,54,'在正确认识和处理社会主义社会矛盾的问题上，我党提出并回答了哪些重要的理论问题（     ）','ABC',2);
insert into question values(814,4,55,'下列关于社会主义基本矛盾的表述，正确的是(     )','ACDE',2);
insert into question values(815,4,56,'下列属于人民内部矛盾的有（    ）','ABCDE',2);
insert into question values(816,4,57,'毛泽东强调，我们在处理人民内部矛盾时要采取民主的方法。所谓民主的方法，包括(    )','ABD',2);
insert into question values(817,4,58,'毛泽东关于社会主义社会矛盾的学说，具有怎样的历史意义(      )','ABCDE',2);
insert into question values(818,4,59,'在走中国工业化道路的探索中，毛泽东提出了一整套“两条腿走路”的方针。以下属于这一方针的是(     )','ABCD',2);
insert into question values(819,4,60,'毛泽东提出社会主义现代化的战略目标是四个现代化，指的是(     )','ABCD',2);
insert into question values(820,4,61,'在所有制结构调整问题上，党和国家的领导人提出了“三个主体、三个补充”的思想， 指的是(     )','ABD',2);
insert into question values(821,4,62,'关于经济运行机制方面，毛泽东提出了“两参一改三结合”的思路。其中包括（     ）','ABCDE',2);
insert into question values(822,4,63,'党的八大提出，要进一步扩大民主，开展反对官僚主义的斗争，就要做到（    ）','ABCDE',2);
insert into question values(823,4,64,'下列属于社会主义建设道路初步探索的重要理论成果的有（     ）','ABC',2);
insert into question values(824,4,65,'社会主义建设道路的初步探索为开创中国特色社会主义提供了(     )','BCD',2);
insert into question values(825,4,66,'社会主义建设道路初步探索留下的经验教训有（     ）','ABCDE',2);
insert into question values(826,5,54,'认清国情，最重要的是要搞清楚两个问题（    ）','BC',2);
insert into question values(827,5,55,'邓小平认为，从1956年中国进入社会主义算起，到中国基本实现现代化，至少需要上百年时间，而巩固和发展社会主义制度，则需要更长的时间。其依据是：(     )','ACD',2);
insert into question values(828,5,56,'党的十六大指出：认清中国的国情，认清中国正处在社会主义初级阶段，是认清社会主义建设一切问题的根据。这是因为社会主义初级阶段理论(    )','ABCD',2);
insert into question values(829,5,57,'我国现代化建设的长期性是由哪些因素决定的（    ）','ABE',2);
insert into question values(830,5,58,'社会主义初级阶段的涵义是(      )','AC',2);
insert into question values(831,5,59,'社会主义初级阶段是我国建设社会主义不可逾越的一个历史阶段(  )','BCDE',2);
insert into question values(832,5,60,'认清当前中国的基本国情，最重要的是要认清两个方面 (    )','BC',2);
insert into question values(833,5,61,'改革开放前在对国情问题的把握上，中国共产党（）','AD',2);
insert into question values(834,5,62,'社会主义初级阶段与新民主主义社会的区别在于（）','ABD',2);
insert into question values(835,5,63,'下列属于社会主义初级阶段特征的是（  ）','ABCDE',2);
insert into question values(836,5,64,'改革开放以来我国在诸多方面都发生了重大变化，但是没有变化的是（  ）','BDE',2);
insert into question values(837,5,65,'邓小平曾指出：“现在虽说我们也在搞社会主义，但事实上不够格”。所谓“不够格”包括（  ）','ABC',2);
insert into question values(838,5,66,'初级阶段长期性的根本决定因素包括（  ）','AC',2);
insert into question values(839,5,67,'社会主义初级阶段理论的重要意义是 (       )','ABCD',2);
insert into question values(840,5,68,'下列关于社会主义初级阶段的基本路线的论述，正确的是(    )','ABCDE',2);
insert into question values(841,5,69,'经济建设、改革开放、四项基本原则的相互关系是(     )','ABC',2);
insert into question values(842,5,70,'“一个中心，两个基本点”是对社会主义初级阶段基本路线的简明概括，“两个基本点”是指（    ）','AB',2);
insert into question values(843,5,71,'实现社会主义初级阶段奋斗目标的根本立足点是（      ）','DE',2);
insert into question values(844,5,72,'属于四项基本原则内容的是（    ）','ABDE',2);
insert into question values(845,5,73,'邓小平说改革是中国的第二次革命，因为改革是（   ）','ABDE',2);
insert into question values(846,5,74,'党的十三大提出的党在社会主义初级阶段基本路线的内容包括','',2);
insert into question values(847,5,75,'下列关于改革开放和四项基本原则的说法正确的是（     ）','ABCD',2);
insert into question values(848,5,76,'党在社会主义初级阶段的奋斗目标是建设（）的社会主义现代化国家','ABCD',2);
insert into question values(849,5,77,'在我们党的历史上曾经五次提出党的总路线或基本路线，其中属于正确的部分是（  ）','ABE',2);
insert into question values(850,5,78,'1979年3月30日在《坚持四项基本原则》的讲话中，邓小平第一次提出了“中国式的现代化”的概念，(    )','ACDE',2);
insert into question values(851,5,79,'关于最高纲领和最低纲领之间的关系论述，正确的是(    )','ABCE',2);
insert into question values(852,5,80,'党在社会主义初级阶段的基本纲领包括(    )','ABCE',2);
insert into question values(853,6,60,'邓小平回答和解决了“什么是社会主义，怎样建设社会主义”这一重大课题意味着（    ）','BCE',2);
insert into question values(854,6,61,'邓小平关于社会主义本质的论断(    )','ABCDE',2);
insert into question values(855,6,62,'解放生产力和发展生产力二者之间的辩证关系是(    )','ABD',2);
insert into question values(856,6,63,'邓小平关于社会主义本质的论断体现了(    )','ABCD',2);
insert into question values(857,6,64,'实现共同富裕是(    )','ACD',2);
insert into question values(858,6,65,'社会主义与资本主义的本质区别在于(    )','ABD',2);
insert into question values(859,6,66,'社会主义制度的基本特征的最重要的方面是(    )','CD',2);
insert into question values(860,6,67,'社会主义的根本任务是发展生产力，这是因为，发展生产力是(    )','ABCD',2);
insert into question values(861,6,68,'发展之所以成为中国共产党执政兴国的第一要务，是因为(    )','ABCD',2);
insert into question values(862,6,69,'邓小平反复强调的两个“搞清楚”是：(    )','AB',2);
insert into question values(863,6,70,'1992年，邓小平在视察南方谈话中，提出判断各方面工作是非、得失的标准是(    )','ABC',2);
insert into question values(864,6,71,'邓小平提出的社会主义的本质的内容是(   )','ABCDE',2);
insert into question values(865,6,72,'邓小平关于社会主义本质的论断，可概括为两个方面的目标。它们是(    )','AB',2);
insert into question values(866,6,73,'邓小平关于社会主义本质的论断具有以下几个显著特点(    )','ABCE',2);
insert into question values(867,6,74,'突出强调的发展是党执政兴国的第一要务的客观依据和历史依据是（    ）','ABCDE',2);
insert into question values(868,6,75,'搞清楚什么是社会主义、怎样建设社会主义( 	  )','ACD',2);
insert into question values(869,6,76,'邓小平回答和解决了“什么是社会主义，怎样建设社会主义”这一重大课题意味着(      )','BD',2);
insert into question values(870,6,77,'之所以说社会主义本质论提高了科学社会主义的认识水平，是因为它()','ABCD',2);
insert into question values(871,6,78,'邓小平关于社会主义本质的科学论断，对建设有中国特色社会主义实践的指导意义(  )','ABCD',2);
insert into question values(872,6,79,'邓小平同志说，“在改革中，我们始终坚持两条根本原则” (	  )','AB',2);
insert into question values(873,6,80,'社会主义与资本主义的本质区别在于 (	  )','ABC',2);
insert into question values(874,6,81,'社会主义本质新概括的重大理论意义在于(	  )','ABC',2);
insert into question values(875,6,82,'邓小平关于社会主义根本任务的主要论点有(	)','ABCD',2);
insert into question values(876,6,83,'社会主义制度的基本特征的最重要的方面是( 	 )','AD',2);
insert into question values(877,6,84,'邓小平的社会主义本质论体现(  	  )','ABCD',2);
insert into question values(878,6,85,'1992年邓小平同志在视察南方的谈话中阐述了一系列重要思想，其中有( 	  )','ABCD',2);
insert into question values(879,6,86,'实现共同富裕是( 	  )','ABD',2);
insert into question values(880,6,87,'邓小平提出社会主义本质理论的过程中，对不符合社会主义本质的思想进行了深刻地剖析，他认为（   ）','ABCDE',2);
insert into question values(881,6,88,'从我国社会主义建设的历史经验来看，过去对什么是社会主义的问题认识不清楚，因此产生了一些错误的思想观念，这些错误的思想观念包括（    ）','ABCD',2);
insert into question values(882,6,89,'邓小平在1992年提出了“发展才是硬道理”著名论断，这一论断的提出（ ）','ABCDE',2);
insert into question values(883,6,90,'中国共产党要始终代表中国先进生产力的发展要求，就必须（    ）','ABCDE',2);
insert into question values(884,6,91,'科学技术实力和国民教育水平始终是衡量综合国力和社会文明程度的标志，也是每个国家走向繁荣昌盛的不可缺少的飞轮。为此党中央相继提出了（    ）','AB',2);
insert into question values(885,6,92,'共同富裕并不意味着（    ）','ABCD',2);
insert into question values(886,6,93,' 1992年邓小平在南方讲话中阐述了一系列重要思想，其中有（    ）','ABDE',2);
insert into question values(887,6,94,'社会主义的根本任务是发展生产力，这是因为，发展生产力是（   ）','ABCDE',2);
insert into question values(888,6,95,'对社会主义本质的概括，体现了（    ）','ABCD',2);
insert into question values(889,6,96,'消除贫困，逐步实现共同富裕是（    ）','ABCD',2);
insert into question values(890,6,97,'社会主义与资本主义区别主要在于（    ）','AB',2);
insert into question values(891,6,98,'关于社会主义本质的概括，其显著特点是突出了（   ）','ABC',2);
insert into question values(892,6,99,'在社会主义初级阶段，必须坚持以经济建设为中心，这是因为只有坚持以经济建设为中心，才能（    ）','ABCDE',2);
insert into question values(893,6,100,'解放生产力和发展生产力的关系是（   ）','ABCE',2);
insert into question values(894,6,101,'邓小平关于社会主义最终是实现共同富裕的论断指明了（    ）','ABDE',2);
insert into question values(895,6,102,'邓小平关于“三个有利于”标准的理论依据是（    ）','CDE',2);
insert into question values(896,6,103,'党的十六大认为我们已经实现的小康有以下哪些特点（  ）','ABD',2);
insert into question values(897,6,104,'在全国31个省市自治区中，15个小康实现程度达90%以上，9个达80～90%，7个在80%以下；目前农村还有3000万人的温饱还没有完全解决，相当数量的人口虽然已经解决了温饱，但还未达到小康。这段材料表明：(    )','ABD',2);
insert into question values(898,6,105,'“三步走”的发展战略是我国社会主义现代化建设的科学的行动纲领，这一发展战略(    )','ABCDE',2);
insert into question values(899,6,106,'世纪头20年，对我国来说，是一个必须紧紧抓住并且可以大有作为的重要战略机遇期，这是因为它是 （    ）','ABD',2);
insert into question values(900,6,107,'“三步走”发展战略的主要内容包括（  ）','ABD',2);
insert into question values(901,6,108,'党的十六大提出在21世纪头20年全面建设小康社会，这是因为(    )','ABCDE',2);
insert into question values(902,6,109,'十七大报告对2020年实现全面建成小康社会的奋斗目标提出了新的更高要求，其中包括(    )','ACDE',2);
insert into question values(903,7,231,'党的纪律处分包括 。 (  )','BCD',2);
insert into question values(904,7,232,'党的主要纪律有(  )。','ABCDEF',2);
insert into question values(905,7,233,'狠抓作风建设，坚决纠正 “四风”，“四风”指的是 。 (  )','BCDE',2);
insert into question values(906,7,234,'党的主要纪律有 。 (  )','ABCDEF',2);
insert into question values(907,7,235,'申请入党的人，要(  )，才能成为正式党员。','ABCD',2);
insert into question values(908,7,236,'党的三大优良传统和作风是指 (  ) 。','ACD',2);
insert into question values(909,7,237,'对“党纪面前人人平等”原则理解正确的是(  )','ABCD',2);
insert into question values(910,7,238,'留党察看期间，受处分党员不享有下列哪些权利。(  )','ABC',2);
insert into question values(911,7,239,'党员拒不执行组织的(  )决定的，给予警告、严重警告或者撤销党内职务处分。','BCD',2);
insert into question values(912,7,240,'《中国共产党纪律处分条例》规定，对党组织和党员违犯党纪的行为，应当以事实为依据，以(  )为准绳，准确地认定违纪性质，区别不同情况，恰当地予以处理。','ABC',2);
insert into question values(913,7,241,'《中国共产党纪律处分条例》规定，下列哪些情形应当给予开除党籍处分。(  )','ABC',2);
insert into question values(914,7,242,'按照《中国共产党纪律处分条例》的规定，下列哪些属于挥霍浪费公共财产行为：(  )','ABCD',2);
insert into question values(915,7,243,'按照《中国共产党纪律处分条例》的规定，贪污(  )款物的，从重或加重处分。','ABC',2);
insert into question values(916,7,244,'中央“八项规定”要求，要精简会议活动，切实改进会风;提高会议实效，(  )。','ABCD',2);
insert into question values(917,7,245,'《中国共产党章程》规定“必须按照中国特色社会主义事业总体布局，全面推进（）。','ABCDE',2);
insert into question values(918,7,246,'申请加入中国共产党的条件是（）。','ABCD',2);
insert into question values(919,7,247,'党的地方各级代表大会和基层代表大会的选举，如果发生违反党章的情况，上一级党的委员会在调查核实后，应作出（）的决定，并报再上一级党的委员会审查批准，正式宣布执行。','AB',2);
insert into question values(920,7,248,'选举人有（）的权利。任何组织和个人不得以任何方式强迫选举人选举或不选举某个人。','ABC',2);
insert into question values(921,7,249,'党坚持（）的方针，建立健全惩治和预防腐败体系，坚持不懈地反对腐败，加强党风建设和廉政建设。','ABCD',2);
insert into question values(922,7,250,'党要适应改革开放和社会主义现代化建设的要求，坚持（），加强和改善党的领导。','ACD',2);
insert into question values(923,7,251,'党的基层组织要对党员进行（），提高党员素质，增强党性。','ABCD',2);
insert into question values(924,7,252,'党章指出，我国社会主义建设的根本任务是（），并且为此而改革生产关系和上层建筑中不适应生产力发展的方面和环节。','ABD',2);
insert into question values(925,7,253,'党章指出，我国现代化建设必须促进（）同步发展。','ABCD',2);
insert into question values(926,7,254,'党章指出，社会主义精神文明能为改革开放和社会主义现代化建设提供强大的（）','ABD',2);
insert into question values(927,7,255,'党章指出，党要适应改革开放和社会主义建设的要求，坚持（），加强和改善党的领导。','ABD',2);
insert into question values(928,7,256,'每个党员，不论职务高低，都必须编入党的一个（），参加党的组织生活，接受党内外群众的监督。','ABD',2);
insert into question values(929,7,257,'党的领导原则是（）','AB',2);
insert into question values(930,7,258,'党章规定，党的最高领导机关是（）。','CD',2);
insert into question values(931,7,259,'《中国共产党章程》归纳了改革开放以来所取得成绩和进步的根本原因“改革开放以来我们取得一切成绩和进步的根本原因，归结起来就是：（）。”','ABC',2);
insert into question values(932,7,260,'《党章》规定，党的建设的基本要求是 (  )。','ABCD',2);
insert into question values(933,7,261,'做好各项工作的总的出发点和检验标准是 ()','ABD',2);
insert into question values(934,7,262,'我国现代化建设必须促进() 同步发展。','ABCD',2);
insert into question values(935,7,263,'预备党员的权利，除了没有()以外，也同正式党员一样。','ABD',2);
insert into question values(936,7,264,'中国共产主义青年团是广大青年在实践中学习中国特色社会主义和共产主义的学校，是党的 ()。','AC',2);
insert into question values(937,7,265,'党的十八大的主题是 。()','ABCD',2);
insert into question values(938,7,266,'任何组织或者个人都不得有超越宪法和法律的特权，绝不允许 ()。','ABD',2);
insert into question values(939,7,267,'下列属于中共中央改进工作作风、密切联系群众的八项规定内容的是(  ) 。','ABCD',2);
insert into question values(940,7,268,'我们一定要毫不动摇坚持与时俱进发展中国特色社会主义，不断丰富中国特色社会主义的 ()。','ABCD',2);
insert into question values(941,7,269,'党巩固执政地位和实现执政使命必须解决好的重大课题是 ()。','ABCD',2);
insert into question values(942,7,270,'与2013年12月印发的《中国共产党纪律处分条例》相比，2015年修订的《中国共产党纪律处分条例》在指导思想上新增了哪些内容?()','BCD',2);
insert into question values(943,7,271,'根据《中国共产党纪律处分条例》，有下列情形之一的，应当从重或者加重处分。()','ABD',2);
insert into question values(944,7,272,'《中国共产党纪律处分条例》规定，有下列行为之一的，给予警告或者严重警告处分;情节较重的，给予撤销党内职务或者留党察看处分;情节严重的，给予开除党籍处分。()','ABC',2);
insert into question values(945,7,273,'《中国共产党纪律处分条例》规定，党员被依法逮捕的，党组织应当按照管理权限中止其()等党员权利。','BCD',2);
insert into question values(946,7,274,'根据《中国共产党纪律处分条例》，主动交代，是指涉嫌违纪的党员：()','AB',2);
insert into question values(947,7,275,'我们党担负着团结带领人民（）的重任。','BCD',2);
insert into question values(948,7,276,'（），都要求我们以改革创新精神全面推进党的建设新的伟大工程，全面提高党的建设科学化水平。','BCD',2);
insert into question values(949,7,277,'党的十八大报告中提出的“坚定理想信念，坚守共产党人精神追求”要抓住的三个重要方面是（）','ABD',2);
insert into question values(950,7,278,'十八大报告强调，要教育引导党员、干部模范践行社会主义荣辱观，讲党性、重品行、作表率，做（），以实际行动彰显共产党人的人格力量。','ABC',2);
insert into question values(951,7,279,'十八大报告提出，面对人民的信任和重托，面对新的历史条件和考验，全党必须增强“四个意识”（）','ABCD',2);
insert into question values(952,7,280,'坚持和发展中国特色社会主义，关键在于建设一支（）的执政骨干队伍。','ABCD',2);
insert into question values(953,7,281,'中国共产党要团结带领全国各族人民，努力实现全面建成小康社会各项目标任务，继续实现（）三大历史任务。','ACD',2);
insert into question values(954,7,282,'实现党的十八大确定的奋斗目标，实现中华民族伟大复兴的中国梦，必须紧紧依靠人民，充分调动广大人民的（）。','ACD',2);
insert into question values(955,7,283,'反腐倡廉必须常抓不懈，拒腐防变必须警钟长鸣，坚持“老虎”、“苍蝇”一起打，切实维护人民合法权益，努力做到（）。','ABD',2);
insert into question values(956,7,284,' 对我国传统文化和外来优秀文化，要坚持（），经过科学的扬弃后使之为我所用。','ABCD',2);
insert into question values(957,7,285,'党的群众路线教育实践活动的主要任务是聚焦到作风建设上，全体共产党员要坚定理想信念，弘扬党的光荣传统和优良作风，集中解决（）“四风”问题，永葆共产党人政治本色。','ABCD',2);
insert into question values(958,7,286,' 党的十八大要求全党坚定对中国特色社会主义的（）','ACD',2);
insert into question values(959,7,287,' 我国发展仍面临不少风险和挑战，主要有（）。','ABCDE',2);
insert into question values(960,7,288,'全党同志一定要以更加坚定的信念、更加顽强的努力，毫不动摇坚持、与时俱进发展中国特色社会主义，不断丰富中国特色社会主义的（）。','ABCD',2);
insert into question values(961,7,289,'邓小平同志开创了中国特色社会主义，第一次比较系统地初步回答了在中国这样经济文化比较落后的国家（）一系列基本问题。','AB',2);
insert into question values(962,7,290,'在全面推进党的建设的道路上，我们要增强自我净化、自我完善、自我革新、自我提高能力，建设（）的马克思主义执政党。','ABC',2);
insert into question values(963,7,291,'我们要继续完善中国特色社会主义法律体系，把国家各项事业和各项工作纳入法制轨道，实行（），维护社会公平正义，实现国家和社会生活制度化、法制化。','ABCD',2);
insert into question values(964,7,292,'我们要按照十八大提出的培育和践行社会主义核心价值观的要求，高度重视和切实加强道德建设，推进（）教育。','ABCD',2);
insert into question values(965,7,293,'对兵团干部职工要从（），吸引更多地方各族干部人才到兵团工作。','BCD',2);
insert into question values(966,7,294,'党的十八大高举中国特色社会主义伟大旗帜，以马列主义、（）为指导，分析了国际国内形势的发展变化。','ABCD',2);
insert into question values(967,7,295,' 我国实施《宪法》过程中取得了巨大的成绩，但是也存在一些不足，主要表现在：（）。','ABCD',2);
insert into question values(968,7,296,' 到中华人民共和国成立一百周年时，把我国建设成为（）的社会主义现代化国家。','ABCD',2);
insert into question values(969,7,297,' 我们必须看到，面对世情、国情、党情的深刻变化，（）更加尖锐地摆在全党面前。','ABCD',2);
insert into question values(970,7,298,' 当前和今后一个时期，兵团要重点抓好以下几点工作（）。','ABCDE',2);
insert into question values(971,7,299,'全党都要站在战略和全局高度来认识新疆工作的重要性，多算大账，少算小账，特别要（），共同努力，实现新疆社会稳定和长治久安。','ABCD',2);
insert into question values(972,7,300,'推进生态文明建设，必须以邓小平理论、“三个代表”重要思想、科学发展观为指导，树立（）的生态文明理念。','ACD',2);
